import * as z from "zod"

export const ProfileElementSchema = z.object({
  id: z.any(),
  name: z.any(),
  active: z.any(),
  address_home_id: z.any(),
  ssnid: z.any(),
  sinid: z.any(),
  bank_account_id: z.any(),
  permit_no: z.any(),
  visa_no: z.any(),
  visa_expire: z.any(),
  image: z.any(),
  image_medium: z.any(),
  image_small: z.any(),
  address_id: z.any(),
  work_phone: z.any(),
  work_email: z.any(),
  work_location: z.any(),
  job_id: z.any(),
  department_id: z.any(),
  child_ids: z.any(),
  coach_id: z.any(),
  category_ids: z.any(),
  notes: z.any(),
  color: z.any(),
  barcode: z.any(),
  pin: z.any(),
  attendance_ids: z.any(),
  direct_badge_ids: z.any(),
  slip_ids: z.any(),
  calendar_id: z.any(),
  is_exempt: z.any(),
  summary_ids: z.any(),
  number: z.any(),
  display_name_en: z.any(),
  gender: z.any(),
  marital: z.any(),
  identification_date: z.any(),
  identification_place: z.any(),
  father_name: z.any(),
  grandfather_name: z.any(),
  grandfather2_name: z.any(),
  family_name: z.any(),
  father_middle_name: z.any(),
  grandfather_middle_name: z.any(),
  complete_name: z.any(),
  mobile_phone: z.any(),
  mobile_phone2: z.any(),
  work_email2: z.any(),
  birthday_location: z.any(),
  attachments: z.any(),
  recruiter_id: z.any(),
  recruiter_date: z.any(),
  employee_state: z.any(),
  emp_state: z.any(),
  state: z.any(),
  religion_id: z.any(),
  external_decision: z.any(),
  begin_work_date: z.any(),
  is_member: z.any(),
  is_saudian: z.any(),
  residence_id: z.any(),
  residence_date: z.any(),
  residence_place: z.any(),
  date_expiration_residence: z.any(),
  place_of_birth_id: z.any(),
  country_id: z.any(),
  passport_date: z.any(),
  passport_place: z.any(),
  passport_end_date: z.any(),
  identity: z.any(),
  identity_date: z.any(),
  identity_place: z.any(),
  identity_end_date: z.any(),
  royal_decree_number: z.any(),
  royal_decree_date: z.any(),
  type_id: z.any(),
  grade_id: z.any(),
  degree_id: z.any(),
  bank_account_ids: z.any(),
  parent_id: z.any(),
  sector_manager_id: z.any(),
  replace_employee_id: z.any(),
  history_ids: z.any(),
  update_ids: z.any(),
  import_note: z.any(),
  sector_id: z.any(),
  administration_id: z.any(),
  insurance_number: z.any(),
  passport_number: z.any(),
  english_name: z.any(),
  birthday: z.any(),
  identification_id: z.any(),
  passport_id: z.any(),
  blood_type: z.any(),
  is_contract: z.any(),
  partner_id: z.any(),
  company_partner_id: z.any(),
  job_title: z.any(),
  phone_number: z.any(),
  mobile_number: z.any(),
  contract_name: z.any(),
  contract_date_from: z.any(),
  contract_date_to: z.any(),
  department_global_id: z.any(),
  is_organisation_development: z.any(),
  is_organisation_development_copy: z.any(),
  deputation_ids: z.any(),
  designation_ids: z.any(),
  distance_work_ids: z.any(),
  evaluation_level_ids: z.any(),
  academic_ids: z.any(),
  service_duration: z.any(),
  experience_ids: z.any(),
  holidays: z.any(),
  holidays_balance: z.any(),
  compensation_stock: z.any(),
  medical_insurance_ids: z.any(),
  take_location_allowance: z.any(),
  take_job_allowance: z.any(),
  take_transport_car: z.any(),
  registered_social_insurance: z.any(),
  is_taken_social_insurance_first_time: z.any(),
  latitude: z.any(),
  longitude: z.any(),
  ldap_id: z.any(),
  manager: z.any(),
  medic_exam: z.any(),
  place_of_birth: z.any(),
  children: z.any(),
  vehicle: z.any(),
  vehicle_distance: z.any(),
  contract_ids: z.any(),
  members_ids: z.any(),
  passport_image: z.any(),
  replace_employee_evaluation_id: z.any(),
  location_id: z.any(),
  UserFlexID: z.any(),
  resource_id: z.any(),
  company_id: z.any(),
  message_follower_ids: z.any(),
  message_ids: z.any(),
  message_last_post: z.any(),
  website_message_ids: z.any(),
  create_uid: z.any(),
  create_date: z.any(),
  write_uid: z.any(),
  write_date: z.any(),
  user_id: z.any(),
  is_address_home_a_company: z.any(),
  last_attendance_id: z.any(),
  manual_attendance: z.any(),
  goal_ids: z.any(),
  badge_ids: z.any(),
  has_badges: z.any(),
  remaining_leaves: z.any(),
  current_leave_id: z.any(),
  leave_date_from: z.any(),
  leave_date_to: z.any(),
  leaves_count: z.any(),
  show_leaves: z.any(),
  is_absent_totay: z.any(),
  newly_hired_employee: z.any(),
  current_leave_state: z.any(),
  attendance_state: z.any(),
  show_mobile: z.any(),
  age: z.any(),
  age_display: z.any(),
  branch_id: z.any(),
  contracts_count: z.any(),
  deputation_balance: z.any(),
  distance_work_balance: z.any(),
  service_duration_display: z.any(),
  normal_holiday_stock: z.any(),
  net_salary: z.any(),
  is_has_edition_authority: z.any(),
  contract_id: z.any(),
  role: z.any(),
  is_have_pic: z.any(),
  job_english_name: z.any(),
  resource_calendar_id: z.any(),
  message_is_follower: z.any(),
  message_partner_ids: z.any(),
  message_channel_ids: z.any(),
  message_unread: z.any(),
  message_unread_counter: z.any(),
  message_needaction: z.any(),
  message_needaction_counter: z.any(),
  display_name: z.any(),
  __last_update: z.any(),
})
export type ProfileElement = z.infer<typeof ProfileElementSchema>

// export const ProfileElementSchema = z.object({
//   id: z.number(),
//   name: z.string(),
//   active: z.boolean(),
//   address_home_id: z.boolean(),
//   ssnid: z.boolean(),
//   sinid: z.boolean(),
//   bank_account_id: z.boolean(),
//   permit_no: z.boolean(),
//   visa_no: z.boolean(),
//   visa_expire: z.boolean(),
//   image: z.string(),
//   image_medium: z.string(),
//   image_small: z.string(),
//   address_id: z.boolean(),
//   work_phone: z.string(),
//   work_email: z.string(),
//   work_location: z.string().or(z.boolean()),
//   job_id: z.array(z.union([z.number(), z.string()])),
//   department_id: z.array(z.union([z.number(), z.string()])),
//   child_ids: z.array(z.number()),
//   coach_id: z.boolean(),
//   category_ids: z.array(z.any()),
//   notes: z.boolean(),
//   color: z.number(),
//   barcode: z.string(),
//   pin: z.string(),
//   attendance_ids: z.array(z.number()),
//   direct_badge_ids: z.array(z.any()),
//   slip_ids: z.array(z.number()),
//   calendar_id: z.array(z.union([z.number(), z.string()])),
//   is_exempt: z.boolean(),
//   summary_ids: z.array(z.any()),
//   number: z.string(),
//   display_name_en: z.boolean(),
//   gender: z.string(),
//   marital: z.string(),
//   identification_date: z.boolean(),
//   identification_place: z.boolean(),
//   father_name: z.string(),
//   grandfather_name: z.string(),
//   grandfather2_name: z.boolean(),
//   family_name: z.string(),
//   father_middle_name: z.string(),
//   grandfather_middle_name: z.string(),
//   complete_name: z.string(),
//   mobile_phone: z.string(),
//   mobile_phone2: z.string().or(z.boolean()),
//   work_email2: z.string(),
//   birthday_location: z.boolean(),
//   attachments: z.array(z.any()),
//   recruiter_id: z.boolean(),
//   recruiter_date: z.string(),
//   employee_state: z.string(),
//   emp_state: z.string(),
//   state: z.boolean(),
//   religion_id: z.array(z.union([z.number(), z.string()])),
//   external_decision: z.boolean(),
//   begin_work_date: z.string(),
//   is_member: z.boolean(),
//   is_saudian: z.boolean(),
//   residence_id: z.boolean(),
//   residence_date: z.boolean(),
//   residence_place: z.boolean(),
//   date_expiration_residence: z.boolean(),
//   place_of_birth_id: z.array(z.union([z.number(), z.string()])).or(z.boolean()),
//   country_id: z.array(z.union([z.number(), z.string()])),
//   passport_date: z.boolean(),
//   passport_place: z.boolean(),
//   passport_end_date: z.boolean().or(z.string()),
//   identity: z.boolean(),
//   identity_date: z.boolean(),
//   identity_place: z.boolean(),
//   identity_end_date: z.boolean(),
//   royal_decree_number: z.boolean(),
//   royal_decree_date: z.boolean(),
//   type_id: z.array(z.union([z.number(), z.string()])),
//   grade_id: z.array(z.union([z.number(), z.string()])),
//   degree_id: z.array(z.union([z.number(), z.string()])),
//   bank_account_ids: z.array(z.number()),
//   parent_id: z.array(z.union([z.number(), z.string()])),
//   sector_manager_id: z.array(z.union([z.number(), z.string()])),
//   replace_employee_id: z.boolean(),
//   history_ids: z.array(z.number()),
//   update_ids: z.array(z.number()),
//   import_note: z.boolean(),
//   sector_id: z.array(z.union([z.number(), z.string()])),
//   administration_id: z.array(z.union([z.number(), z.string()])),
//   insurance_number: z.string(),
//   passport_number: z.string(),
//   english_name: z.string(),
//   birthday: z.string(),
//   identification_id: z.string(),
//   passport_id: z.boolean(),
//   blood_type: z.string(),
//   is_contract: z.boolean(),
//   partner_id: z.boolean(),
//   company_partner_id: z.boolean(),
//   job_title: z.boolean(),
//   phone_number: z.boolean(),
//   mobile_number: z.boolean(),
//   contract_name: z.boolean(),
//   contract_date_from: z.boolean(),
//   contract_date_to: z.boolean(),
//   department_global_id: z.array(z.union([z.number(), z.string()])),
//   is_organisation_development: z.boolean(),
//   is_organisation_development_copy: z.boolean(),
//   deputation_ids: z.array(z.number()),
//   designation_ids: z.array(z.number()),
//   distance_work_ids: z.array(z.number()),
//   evaluation_level_ids: z.array(z.any()),
//   academic_ids: z.array(z.number()),
//   service_duration: z.number(),
//   experience_ids: z.array(z.any()),
//   holidays: z.array(z.number()),
//   holidays_balance: z.array(z.number()),
//   compensation_stock: z.number(),
//   medical_insurance_ids: z.array(z.number()),
//   take_location_allowance: z.boolean(),
//   take_job_allowance: z.boolean(),
//   take_transport_car: z.boolean(),
//   registered_social_insurance: z.string(),
//   is_taken_social_insurance_first_time: z.boolean(),
//   latitude: z.number(),
//   longitude: z.number(),
//   ldap_id: z.string(),
//   manager: z.boolean(),
//   medic_exam: z.boolean(),
//   place_of_birth: z.boolean(),
//   children: z.number(),
//   vehicle: z.boolean(),
//   vehicle_distance: z.number(),
//   contract_ids: z.array(z.number()),
//   members_ids: z.array(z.any()),
//   passport_image: z.boolean().or(z.string()),
//   replace_employee_evaluation_id: z.boolean(),
//   location_id: z.array(z.union([z.number(), z.string()])),
//   UserFlexID: z.string(),
//   resource_id: z.array(z.union([z.number(), z.string()])),
//   company_id: z.array(z.union([z.number(), z.string()])),
//   message_follower_ids: z.array(z.any()),
//   message_ids: z.array(z.number()),
//   message_last_post: z.boolean(),
//   website_message_ids: z.array(z.any()),
//   create_uid: z.array(z.union([z.number(), z.string()])),
//   create_date: z.coerce.date(),
//   write_uid: z.array(z.union([z.number(), z.string()])),
//   write_date: z.coerce.date(),
//   user_id: z.array(z.union([z.number(), z.string()])),
//   is_address_home_a_company: z.boolean(),
//   last_attendance_id: z.array(z.union([z.number(), z.string()])),
//   manual_attendance: z.boolean(),
//   goal_ids: z.array(z.any()),
//   badge_ids: z.array(z.any()),
//   has_badges: z.boolean(),
//   remaining_leaves: z.number(),
//   current_leave_id: z.any(),
//   leave_date_from: z.boolean().or(z.string()),
//   leave_date_to: z.boolean().or(z.string()),
//   leaves_count: z.number(),
//   show_leaves: z.boolean(),
//   is_absent_totay: z.boolean(),
//   newly_hired_employee: z.boolean(),
//   current_leave_state: z.boolean().or(z.string()),
//   attendance_state: z.string(),
//   show_mobile: z.boolean(),
//   age: z.number(),
//   age_display: z.string(),
//   branch_id: z.array(z.union([z.number(), z.string()])),
//   contracts_count: z.number(),
//   deputation_balance: z.number(),
//   distance_work_balance: z.number(),
//   service_duration_display: z.string(),
//   normal_holiday_stock: z.number(),
//   net_salary: z.number(),
//   is_has_edition_authority: z.boolean(),
//   contract_id: z.array(z.union([z.number(), z.string()])),
//   role: z.string(),
//   is_have_pic: z.boolean(),
//   job_english_name: z.string(),
//   resource_calendar_id: z.array(z.union([z.number(), z.string()])),
//   message_is_follower: z.boolean(),
//   message_partner_ids: z.array(z.any()),
//   message_channel_ids: z.array(z.any()),
//   message_unread: z.boolean(),
//   message_unread_counter: z.number(),
//   message_needaction: z.boolean(),
//   message_needaction_counter: z.number(),
//   display_name: z.string(),
//   __last_update: z.coerce.date(),
// })
// export type ProfileElement = z.infer<typeof ProfileElementSchema>
