import type { GeneralInfo } from "@types"

export const defaultGeneralInfo: GeneralInfo[] = [
  {
    title: "طلب الموظفين",
    active: true,
    index: 0,
    key: "employeeRequests",
    icon: "RequestsIcon",
    backgroundColor: "#474A9B24",
    count: 200,
    link: "#",
    id: -1,
    userId: -1,
  },
  {
    title: "طلبات الموافقة",
    active: true,
    index: 1,
    key: "approvalRequests",
    icon: "ApprovalsIcon",
    backgroundColor: "#754B9F24",
    count: 258,
    link: "#",
    id: -2,
    userId: -1,
  },
  {
    title: "اجمالي رصيد الاجازات",
    active: true,
    index: 2,
    icon: "VacationIcon",
    key: "totalVacationBalance",
    backgroundColor: "#9A407D24",
    count: 285,
    link: "#",
    id: -3,
    userId: -1,
  },
  {
    title: "الاستئذان",
    active: true,
    index: 3,
    icon: "PerformanceIcon",
    key: "permissions",
    backgroundColor: "#AC2A5624",
    count: 325,
    link: "#",
    id: -4,
    userId: -1,
  },
  {
    title: "العمل عن بعد",
    active: true,
    index: 4,
    icon: "RemoteWorkIcon",
    key: "remoteWork",
    backgroundColor: "#F7893224",
    count: 200,
    link: "#",
    id: -5,
    userId: -1,
  },
  {
    title: "الانتدابات",
    active: true,
    index: 5,
    icon: "TimeIcon",
    key: "delegations",
    backgroundColor: "#F1514324",
    count: 200,
    link: "#",
    id: -6,
    userId: -1,
  },
  {
    title: "طلبات الشراء",
    active: false,
    index: 6,
    icon: "SearchListIcon",
    key: "purchaseRequests",
    backgroundColor: "#28B7D523",
    count: 200,
    link: "#",
    id: -7,
    userId: -1,
  },
  {
    title: "خطابات الموارد البشرية",
    active: false,
    index: 7,
    icon: "MailboxIcon",
    key: "hrLetters",
    backgroundColor: "#0B699C23",
    count: 200,
    link: "#",
    id: -8,
    userId: -1,
  },
  {
    title: "طلبات العمل الإضافي",
    active: false,
    index: 8,
    icon: "WritingNoteIcon",
    key: "overtimeRequests",
    backgroundColor: "#4FC0AE23",
    count: 200,
    link: "#",
    id: -9,
    userId: -1,
  },
  {
    title: "طلبات تبرير الحضور والانصراف",
    active: false,
    index: 9,
    icon: "TabletIcon",
    key: "justificationRequests",
    backgroundColor: "#63C08B23",
    count: 200,
    link: "#",
    id: -10,
    userId: -1,
  },
  {
    title: "طلبات التغيير",
    active: false,
    index: 10,
    icon: "TabletAltIcon",
    key: "changeRequests",
    backgroundColor: "#BFD45123",
    count: 200,
    link: "#",
    id: -11,
    userId: -1,
  },
  {
    title: "طلب العهدة",
    key: "custodyRequests",
    active: false,
    index: 11,
    icon: "DeliveryIcon",
    backgroundColor: "#FDBB3923",
    count: 200,
    link: "#",
    id: -12,
    userId: -1,
  },
] as const
