//TODO: rename titles and keys
import type { GeneralInfo } from "@types"

export const defaultGeneralInfo: GeneralInfo[] = [
  {
    title: "الرصيد الحالي",
    active: true,
    index: 0,
    key: "current_holidays_stock",
    icon: "RequestsIcon",
    backgroundColor: "#474A9B24",
    count: 200,
    link: "#",
    id: -1,
    userId: -1,
  },
  {
    title: "الرصيد ما قبل اللائحة",
    active: true,
    index: 1,
    key: "old_holidays_stock",
    icon: "ApprovalsIcon",
    backgroundColor: "#754B9F24",
    count: 258,
    link: "#",
    id: -2,
    userId: -1,
  },
  {
    title: "الاجازات تحت الإجراء",
    active: true,
    index: 2,
    icon: "VacationIcon",
    key: "pending_holidays_requests",
    backgroundColor: "#9A407D24",
    count: 285,
    link: "#",
    id: -3,
    userId: -1,
  },
  {
    title: "الاجازات المعتمدة",
    active: true,
    index: 3,
    icon: "PerformanceIcon",
    key: "done_holidays_requests",
    backgroundColor: "#AC2A5624",
    count: 325,
    link: "#",
    id: -4,
    userId: -1,
  },
  {
    title: "المرفوضة /  والملغاة",
    key: "refused_cancelled_holidays_requests",
    active: true,
    index: 3,
    icon: "PerformanceIcon",
    backgroundColor: "#AC2A5624",
    count: 325,
    link: "#",
    id: -4,
    userId: -1,
  },
  {
    title: "كل الاجازات",
    key: "all_holidays",
    active: true,
    index: 3,
    icon: "PerformanceIcon",
    backgroundColor: "#AC2A5624",
    count: 325,
    link: "#",
    id: -4,
    userId: -1,
  },
] as const
