import type { HomePageSlot } from '@types';

export const defaultHomePageSlots: HomePageSlot[] = [
  {
    id: -1,
    title: 'اكتمال الملف الشخصي',
    key: 'completeProfile',
    active: true,
    index: 0,
    slotType: 'homePage',
    userId: -1,
  },
  {
    id: -2,
    title: 'المؤشرات',
    key: 'generalInfo',
    active: true,
    index: 1,
    slotType: 'homePage',
    userId: -1,
  },
  {
    id: -3,
    title: 'بياناتي',
    key: 'userInfo',
    active: true,
    index: 2,
    slotType: 'homePage',
    userId: -1,
  },
  {
    id: -4,
    title: 'الحضور والانصراف',
    key: 'attendance',
    active: true,
    index: 3,
    slotType: 'homePage',
    userId: -1,
  },
  {
    id: -5,
    title: 'طلباتي',
    key: 'approvalRequestsTable',
    active: true,
    index: 4,
    slotType: 'homePage',
    userId: -1,
  },
  {
    title: 'في نفس الادارة',
    id: -6,
    key: 'sliders',
    active: true,
    index: 5,
    slotType: 'homePage',
    userId: -1,
  },
  {
    title: 'الجدول الزمني',
    id: -7,
    key: 'timelineCalendar',
    active: true,
    index: 6,
    slotType: 'homePage',
    userId: -1,
  },
  {
    title: 'الاخبار والاعلانات',
    id: -8,
    key: 'news',
    active: true,
    index: 7,
    slotType: 'homePage',
    userId: -1,
  },
] as const;
