export { colors } from "./colors"
// export { defaultGeneralInfo } from "./defaultGeneralInfo"
export { defaultHomePageSlots } from "./defaultHomePagSlots"
export { defaultNewsTabs } from "./defaultNewsTabs"
export { fonts } from "./fonts"
export { generalInfoKeys } from "./generalInfoKeys"
export { homePageSlotsKeys } from "./homePageSlotsKeys"
export { keyboardAlphaNumericKeys } from "./keyboardAlphaNumericKeys"
export { modalPaths } from "./modalPaths"
export { newsTabsKeys } from "./newsTabsKeys"
export { paths } from "./paths"
export { ErrorCode as ErrorMessage } from "./ErrorCode"
