import * as z from "zod"

export const OvertimeConfirmElementSchema = z.object({
  id: z.number(),
  name: z.string(),
  date: z.string(),
  employee_id: z.array(z.union([z.number(), z.string()])),
  nb_extras_time: z.number(),
  overtime_assignment_id: z.array(z.union([z.number(), z.string()])),
  date_from: z.string(),
  date_to: z.string(),
  nb_hours: z.number(),
  description: z.string(),
  state: z.string(),
  is_added_to_payroll: z.boolean(),
  payslip_run_id: z.boolean(),
  category_name: z.string(),
  benefit_name: z.string(),
  basic_salary: z.number(),
  housing_allow: z.number(),
  transport_allow: z.number(),
  connect_allow: z.number(),
  total_salary: z.number(),
  sequence_temp: z.number(),
  req_sequence_temp: z.number(),
  website_message_ids: z.array(z.number()),
  message_follower_ids: z.array(z.number()),
  message_ids: z.array(z.number()),
  message_last_post: z.boolean(),
  create_uid: z.array(z.union([z.number(), z.string()])),
  create_date: z.coerce.date(),
  write_uid: z.array(z.union([z.number(), z.string()])),
  write_date: z.coerce.date(),
  department_id: z.array(z.union([z.number(), z.string()])),
  job_id: z.array(z.union([z.number(), z.string()])),
  type_job_id: z.array(z.union([z.number(), z.string()])),
  grade_id: z.array(z.union([z.number(), z.string()])),
  is_current_user: z.boolean(),
  is_director: z.boolean(),
  is_administration_manager: z.boolean(),
  is_gm_admin: z.boolean(),
  is_sector_manager: z.boolean(),
  total_nb_extras_time: z.number(),
  total_nb_hours: z.number(),
  individual_net_salary: z.number(),
  can_approve: z.boolean(),
  message_is_follower: z.boolean(),
  message_partner_ids: z.array(z.number()),
  message_channel_ids: z.array(z.any()),
  message_unread: z.boolean(),
  message_unread_counter: z.number(),
  message_needaction: z.boolean(),
  message_needaction_counter: z.number(),
  display_name: z.string(),
  __last_update: z.coerce.date(),
})
export type OvertimeConfirmElement = z.infer<
  typeof OvertimeConfirmElementSchema
>
