trigger:
  - main

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          # Explicit checkout of the repository along with submodules.
          - checkout: self
            submodules: recursive
            displayName: "Checkout repository with submodules"

          # Build the Docker image using the Docker@2 task.
          - task: Docker@2
            displayName: "Build an image"
            env:
              DOCKER_BUILDKIT: 1
            inputs:
              command: build
              dockerfile: "$(Build.SourcesDirectory)/Dockerfile"
              tags: |
                $(tag)
              buildContext: "$(Build.SourcesDirectory)"
