import * as z from "zod"

export const HolidayElementSchema = z.object({
  id: z.any(),
  payslip_status: z.any(),
  report_note: z.any(),
  user_id: z.any(),
  manager_id: z.any(),
  notes: z.any(),
  number_of_days_temp: z.any(),
  number_of_days: z.any(),
  meeting_id: z.any(),
  type: z.any(),
  linked_request_ids: z.any(),
  category_id: z.any(),
  holiday_type: z.any(),
  first_approver_id: z.any(),
  second_approver_id: z.any(),
  name: z.any(),
  date: z.any(),
  employee_id: z.any(),
  substitute_employee_id: z.any(),
  department_id: z.any(),
  job_id: z.any(),
  grade_id: z.any(),
  degree_id: z.any(),
  raison: z.any(),
  date_from: z.any(),
  date_to: z.any(),
  duration: z.any(),
  holiday_status_id: z.any(),
  with_advanced_salary: z.any(),
  salary_number: z.any(),
  state: z.any(),
  holiday_cancellation: z.any(),
  is_extension: z.any(),
  extended_holiday_id: z.any(),
  parent_id: z.any(),
  extension_holidays_ids: z.any(),
  extension_duration: z.any(),
  childbirth_date: z.any(),
  sold_overtime: z.any(),
  sold_attendance: z.any(),
  death_person: z.any(),
  compensation_type: z.any(),
  accompaniment_type: z.any(),
  accompanied_child_age: z.any(),
  study_subject: z.any(),
  city: z.any(),
  country_ids: z.any(),
  current_holiday_stock: z.any(),
  sport_participation_topic: z.any(),
  birth_child_filename: z.any(),
  hide_with_advanced_salary: z.any(),
  token_compensation_stock: z.any(),
  payed_salary_advance: z.any(),
  done_date: z.any(),
  attachment_ids: z.any(),
  date_holidays_to: z.any(),
  refuse_reason: z.any(),
  active: z.any(),
  cancel_reason: z.any(),
  res_model: z.any(),
  is_from_mobile: z.any(),
  mobile_approvals_ids: z.any(),
  message_follower_ids: z.any(),
  message_ids: z.any(),
  message_last_post: z.any(),
  website_message_ids: z.any(),
  create_uid: z.any(),
  create_date: z.any(),
  write_uid: z.any(),
  write_date: z.any(),
  x_sla_labels: z.any(),
  double_validation: z.any(),
  can_reset: z.any(),
  is_annual: z.any(),
  spend_advanced_salary: z.any(),
  advanced_salary_period: z.any(),
  is_current_user: z.any(),
  is_direct_manager: z.any(),
  is_cut: z.any(),
  is_cancelled: z.any(),
  is_started: z.any(),
  is_finished: z.any(),
  is_extended: z.any(),
  can_be_cut: z.any(),
  can_be_cancelled: z.any(),
  display_button_cancel: z.any(),
  display_button_cut: z.any(),
  display_button_extend: z.any(),
  attachment_required: z.any(),
  display_button_send: z.any(),
  substitute_employee_required: z.any(),
  department_global_id: z.any(),
  sector_id: z.any(),
  message_is_follower: z.any(),
  message_partner_ids: z.any(),
  message_channel_ids: z.any(),
  message_unread: z.any(),
  message_unread_counter: z.any(),
  message_needaction: z.any(),
  message_needaction_counter: z.any(),
  display_name: z.any(),
  __last_update: z.any(),
})

export type HolidayElement = z.infer<typeof HolidayElementSchema>

// export const HolidayElementSchema = z.object({
//     "id": z.number(),
//     "payslip_status": z.boolean(),
//     "report_note": z.boolean(),
//     "user_id": z.array(z.union([z.string(), z.number()])),
//     "manager_id": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
//     "notes": z.string(),
//     "number_of_days_temp": z.number(),
//     "number_of_days": z.number(),
//     "meeting_id": z.boolean(),
//     "type": z.string(),
//     "linked_request_ids": z.array(z.any()),
//     "category_id": z.boolean(),
//     "holiday_type": z.string(),
//     "first_approver_id": z.boolean(),
//     "second_approver_id": z.boolean(),
//     "name": z.union([z.string(), z.boolean()]),
//     "date": z.string(),
//     "employee_id": z.array(z.union([z.string(), z.number()])),
//     "substitute_employee_id": z.array(z.union([z.string(), z.number()])),
//     "department_id": z.array(z.union([z.number(), z.string()])),
//     "job_id": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
//     "grade_id": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
//     "degree_id": z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
//     "raison": z.union([z.boolean(), z.string()]),
//     "date_from": z.string(),
//     "date_to": z.string(),
//     "duration": z.number(),
//     "holiday_status_id": z.array(z.union([z.string(), z.number()])),
//     "with_advanced_salary": z.boolean(),
//     "salary_number": z.number(),
//     "state": z.string(),
//     "holiday_cancellation": z.boolean(),
//     "is_extension": z.boolean(),
//     "extended_holiday_id": z.boolean(),
//     "parent_id": z.boolean(),
//     "extension_holidays_ids": z.array(z.any()),
//     "extension_duration": z.number(),
//     "childbirth_date": z.union([z.boolean(), z.string()]),
//     "sold_overtime": z.number(),
//     "sold_attendance": z.number(),
//     "death_person": z.union([z.boolean(), z.string()]),
//     "compensation_type": z.boolean(),
//     "accompaniment_type": z.boolean(),
//     "accompanied_child_age": z.number(),
//     "study_subject": z.boolean(),
//     "city": z.boolean(),
//     "country_ids": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
//     "current_holiday_stock": z.number(),
//     "sport_participation_topic": z.boolean(),
//     "birth_child_filename": z.boolean(),
//     "hide_with_advanced_salary": z.boolean(),
//     "token_compensation_stock": z.number(),
//     "payed_salary_advance": z.boolean(),
//     "done_date": z.string(),
//     "attachment_ids": z.array(z.number()),
//     "date_holidays_to": z.boolean(),
//     "refuse_reason": z.string(),
//     "active": z.boolean(),
//     "cancel_reason": z.boolean(),
//     "res_model": z.string(),
//     "is_from_mobile": z.boolean(),
//     "mobile_approvals_ids": z.array(z.number()),
//     "message_follower_ids": z.array(z.number()),
//     "message_ids": z.array(z.number()),
//     "message_last_post": z.boolean(),
//     "website_message_ids": z.array(z.any()),
//     "create_uid": z.array(z.union([z.string(), z.number()])),
//     "create_date": z.coerce.date(),
//     "write_uid": z.array(z.union([z.string(), z.number()])),
//     "write_date": z.coerce.date(),
//     "x_sla_labels": z.union([z.string(), z.boolean()]),
//     "double_validation": z.boolean(),
//     "can_reset": z.boolean(),
//     "is_annual": z.boolean(),
//     "spend_advanced_salary": z.boolean(),
//     "advanced_salary_period": z.number(),
//     "is_current_user": z.boolean(),
//     "is_direct_manager": z.boolean(),
//     "is_cut": z.boolean(),
//     "is_cancelled": z.boolean(),
//     "is_started": z.boolean(),
//     "is_finished": z.boolean(),
//     "is_extended": z.boolean(),
//     "can_be_cut": z.boolean(),
//     "can_be_cancelled": z.boolean(),
//     "display_button_cancel": z.boolean(),
//     "display_button_cut": z.boolean(),
//     "display_button_extend": z.boolean(),
//     "attachment_required": z.boolean(),
//     "display_button_send": z.boolean(),
//     "substitute_employee_required": z.boolean(),
//     "department_global_id": z.array(z.union([z.string(), z.number()])),
//     "sector_id": z.array(z.union([z.string(), z.number()])),
//     "message_is_follower": z.boolean(),
//     "message_partner_ids": z.array(z.number()),
//     "message_channel_ids": z.array(z.any()),
//     "message_unread": z.boolean(),
//     "message_unread_counter": z.number(),
//     "message_needaction": z.boolean(),
//     "message_needaction_counter": z.number(),
//     "display_name": z.string(),
//     "__last_update": z.coerce.date(),
// });

// export type HolidayElement = z.infer<typeof HolidayElementSchema>;
