"use server"

import { EmployeeMemberSchema } from "@api/schemas/index"
import { ResponseSchema } from "@api/schemas/responseSchema"
import type { EmployeeMembersRequest } from "@types"
import { getData } from "./getData"

export const getEmployeeMembersRequests = async (): Promise<
  EmployeeMembersRequest[]
> => {
  return getData<EmployeeMembersRequest>({
    url: "api/po/hr/employee/members/read",
    additionalBody: { employee_id: Number }, // Ensures employee_id is converted to number
    responseSchema: ResponseSchema,
    dataSchema: EmployeeMemberSchema,
    parseData: (data) => {
      return data.map((item: any) => ({
        id: item.id.toString(),
        date: item.date,
        applicant: item.employee_id[1]
          .toString()
          .replace(/\[\d+\]\s*/, "")
          .split(/\s+/)[0],
        requestType: item.type,
        relation: item.relative_relation,
        nameAr: item.individual_complete_name,
        nameEn: item.individual_english_name,
        idNumber: item.identity,
        birthDate: item.birthday,
        status: item.state,
      }))
    },
    dummyData,
  })
}

const dummyData: EmployeeMembersRequest[] = [
  {
    id: "#55965",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55964",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55963",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55962",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55961",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55960",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55959",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55958",
    date: "2024-05-04",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55957",
    date: "2024-05-04",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55956",
    date: "2024-05-03",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55955",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55954",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55953",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55952",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55951",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55950",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55949",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55948",
    date: "2024-05-04",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55947",
    date: "2024-05-04",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
]
