"use server"

import { EmployeeMemberSchema } from "@api/schemas/index"
import { ResponseSchema } from "@api/schemas/responseSchema"
import type { EmployeeMembersRequest } from "@types"
import { z } from "zod"
import { getData } from "./getData"

export const getEmployeeMembersRequests = async (): Promise<
  EmployeeMembersRequest[]
> => {
  return getData<EmployeeMembersRequest>({
    url: "api/po/hr/employee/members/read",
    includeEmployeeId: true,
    responseSchema: ResponseSchema,
    dataSchema: EmployeeMemberSchema,
    parseData: (data) => {
      return data.map((rawItem: unknown) => {
        const item = rawItem as z.infer<typeof EmployeeMemberSchema>
        const employeeId = Array.isArray(item.employee_id)
          ? item.employee_id[1]
          : ""
        let applicantName = ""

        if (employeeId && typeof employeeId === "string") {
          applicantName = employeeId.replace(/\[\d+\]\s*/, "").split(/\s+/)[0]
        }

        return {
          id: String(item.id || ""),
          date: String(item.date || ""),
          applicant: applicantName,
          requestType: String(item.type || ""),
          relation: String(item.relative_relation || ""),
          nameAr: String(item.individual_complete_name || ""),
          nameEn: String(item.individual_english_name || ""),
          idNumber: String(item.identity || ""),
          birthDate: String(item.birthday || ""),
          status: String(item.state || ""),
        }
      })
    },
    dummyData,
  })
}

const dummyData: EmployeeMembersRequest[] = [
  {
    id: "#55965",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55964",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55963",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55962",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55961",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55960",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55959",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55958",
    date: "2024-05-04",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55957",
    date: "2024-05-04",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55956",
    date: "2024-05-03",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55955",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55954",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55953",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55952",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55951",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
  {
    id: "#55950",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55949",
    date: "2024-05-05",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "المدير المباشر",
  },
  {
    id: "#55948",
    date: "2024-05-04",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "اعتمد",
  },
  {
    id: "#55947",
    date: "2024-05-04",
    applicant: "حمد",
    requestType: "اضافة",
    relation: "أب",
    nameAr: "يوسف حمد عبد الله القشيمط",
    nameEn: "youssef Hamad Abdullah Alqushaymit",
    idNumber: "10326569",
    birthDate: "2024-05-05 ",
    status: "عمليات الموارد البشرية",
  },
]
