import type { RelatedUser } from "@types"
import type { Route } from "next"

export const getRelatedUsers = async (): Promise<RelatedUser[]> => {
  return users
}

const users = [
  {
    id: "220164#",
    name: "سعود القامري",
    position: "مدير عام المرافق والخدمات الادراية",
    image: "/employee-1.svg",
    phone: "0507770500",
    recycleWork: "تحويل العمل 4554",
    address: "المقر الرئيسي - الدور الأرضي",
    email: "hqushaymit@monshaat.gov.sa",
    department: "المرافق والخدمات الادراية",
    workType: "عمل عن بعد",
    link: "#" as Route,
  },
  {
    id: "220165#",
    name: "نورة العتيبي",
    position: "مدير عام المرافق والخدمات الادراية",
    image: "/employee-2.svg",
    phone: "0507770501",
    recycleWork: "تحويل العمل 4554",
    address: "المقر الرئيسي - الدور الأرضي",
    email: "hqushaymit@monshaat.gov.sa",
    department: "المرافق والخدمات الادراية",
    workType: "عمل عن بعد",
    link: "#" as Route,
  },
  {
    id: "220166#",
    name: "عبدالله الشمري",
    position: "مدير عام المرافق والخدمات الادراية",
    image: "/employee-6.svg",
    phone: "0508670500",
    recycleWork: "تحويل العمل 4554",
    address: "المقر الرئيسي - الدور الأرضي",
    email: "hqushaymit@monshaat.gov.sa",
    department: "المرافق والخدمات الادراية",
    workType: "عمل عن بعد",
    link: "#" as Route,
  },
  {
    id: "220167#",
    name: "فاطمة الحربي",
    position: "مدير عام المرافق والخدمات الادراية",
    image: "/employee-5.svg",
    phone: "0507260500",
    recycleWork: "تحويل العمل 4554",
    address: "المقر الرئيسي - الدور الأرضي",
    email: "hqushaymit@monshaat.gov.sa",
    department: "المرافق والخدمات الادراية",
    workType: "عمل عن بعد",
    link: "#" as Route,
  },
  {
    id: "220168#",
    name: "فهد الدوسري",
    position: "مدير عام المرافق والخدمات الادراية",
    image: "/employee-4.svg",
    phone: "0507150500",
    recycleWork: "تحويل العمل 4554",
    address: "المقر الرئيسي - الدور الأرضي",
    email: "hqushaymit@monshaat.gov.sa",
    department: "المرافق والخدمات الادراية",
    workType: "عمل عن بعد",
    link: "#" as Route,
  },
  {
    id: "220169#",
    name: "رهف العبدلله",
    position: "مدير عام المرافق والخدمات الادراية",
    image: "/employee-3.svg",
    phone: "0507890500",
    recycleWork: "تحويل العمل 4554",
    address: "المقر الرئيسي - الدور الأرضي",
    email: "hqushaymit@monshaat.gov.sa",
    department: "المرافق والخدمات الادراية",
    workType: "عمل عن بعد",
    link: "#" as Route,
  },
]
