export type DeputationRequestDetails = {
  id: string;
  requestDate: string;
  deputation: string;
  transportation: string;
  startDate: string;
  endDate: string;
  duration: string;
  city: string;
  deputationType: string;
  task: string;
  taskDetails: string;
  departureDatesStatus: string;
  travelDuration: string;
  travelStartDate: string;
  travelEndDate: string;
  deputationAmount: string;
  transferDate: string;
  reserved: string;
  status: string;
  reason: string;
  notes: string;
  attachments: File[];
};
