import * as z from "zod";


export const DeputationElementSchema = z.object({
    "id": z.number(),
    "seq_number": z.string(),
    "order_date": z.string(),
    "number": z.string(),
    "code": z.boolean(),
    "governmental_entity": z.boolean(),
    "country_id": z.array(z.union([z.number(), z.string()])),
    "number_job": z.boolean(),
    "job_id": z.boolean(),
    "type_id": z.array(z.union([z.number(), z.string()])),
    "department_inter_id": z.boolean(),
    "city_id": z.array(z.union([z.number(), z.string()])),
    "grade_id": z.array(z.union([z.number(), z.string()])),
    "degree_id": z.array(z.union([z.number(), z.string()])),
    "date_from": z.string(),
    "date_to": z.string(),
    "note": z.boolean(),
    "transport_allowance": z.boolean(),
    "allowance_bonus": z.boolean(),
    "the_availability": z.string(),
    "transportation_type": z.string(),
    "type": z.string(),
    "location_ids": z.array(z.any()),
    "state": z.string(),
    "task_name": z.string(),
    "duration": z.number(),
    "salary_grid_type_id": z.array(z.union([z.number(), z.string()])),
    "deputation_type": z.array(z.union([z.number(), z.string()])),
    "deputation_balance_override": z.boolean(),
    "decision_id": z.boolean(),
    "travel_days": z.string(),
    "deputation_allowance": z.number(),
    "amount": z.number(),
    "ticket_amount": z.number(),
    "car_amount": z.number(),
    "ticket_reserved": z.boolean(),
    "total": z.number(),
    "expected_date": z.boolean(),
    "attachment_ids": z.array(z.any()),
    "refuse_reason": z.union([z.boolean(), z.string()]),
    "latitude": z.number(),
    "longitude": z.number(),
    "cancel_reason": z.boolean(),
    "fees_amount": z.number(),
    "need_fees": z.boolean(),
    "distance": z.number(),
    "substitute_employee_id": z.boolean(),
    "active": z.boolean(),
    "deputation_extension_ids": z.array(z.any()),
    "extension_duration": z.number(),
    "token": z.boolean(),
    "is_need_visa": z.boolean(),
    "flight_class": z.string(),
    "flight_number": z.boolean(),
    "flight_date": z.boolean(),
    "flight_air": z.boolean(),
    "ticket_cost": z.number(),
    "itinerary": z.boolean(),
    "reservation_mail_sent": z.boolean(),
    "direct_action_number": z.boolean(),
    "direct_action_date": z.boolean(),
    "direct_action_state": z.boolean(),
    "has_direct_action": z.boolean(),
    "direct_action_attachment_ids": z.array(z.any()),
    "is_long_duration": z.boolean(),
    "date_from_travel": z.string(),
    "date_to_travel": z.string(),
    "travel_days_setting": z.string(),
    "training_request_id": z.boolean(),
    "issue_visa": z.boolean(),
    "payslip_run_id": z.boolean(),
    "is_added_to_payroll": z.boolean(),
    "deputation_sequence_temp": z.number(),
    "deputation_sequence_req": z.number(),
    "total_internal_training_trip_amount": z.number(),
    "total_external_training_trip_amount": z.number(),
    "total_internal_work_trip_amount": z.number(),
    "total_external_work_trip_amount": z.number(),
    "degree": z.boolean(),
    "res_model": z.string(),
    "is_from_mobile": z.boolean(),
    "mobile_approvals_ids": z.array(z.any()),
    "website_message_ids": z.array(z.any()),
    "message_follower_ids": z.array(z.number()),
    "message_ids": z.array(z.number()),
    "message_last_post": z.boolean(),
    "user_id": z.array(z.union([z.number(), z.string()])),
    "employee_id": z.array(z.union([z.number(), z.string()])),
    "department_id": z.array(z.union([z.number(), z.string()])),
    "workflow_id": z.array(z.union([z.number(), z.string()])),
    "step_id": z.array(z.union([z.number(), z.string()])),
    "workflow_user_ids": z.array(z.number()),
    "reason_cancel_wkf": z.boolean(),
    "reason_abort_wkf": z.boolean(),
    "create_uid": z.array(z.union([z.number(), z.string()])),
    "create_date": z.coerce.date(),
    "write_uid": z.array(z.union([z.number(), z.string()])),
    "write_date": z.coerce.date(),
    "x_sla_labels": z.string(),
    "display_button_cancel": z.boolean(),
    "is_direct_manager": z.boolean(),
    "display_button_extend": z.boolean(),
    "display_button_direct_action": z.boolean(),
    "display_button_reserve_ticket": z.boolean(),
    "display_button_cut": z.boolean(),
    "is_current_user": z.boolean(),
    "is_cut": z.boolean(),
    "is_started": z.boolean(),
    "is_finished": z.boolean(),
    "is_extended": z.boolean(),
    "is_sector_manager": z.boolean(),
    "display_travel_dates": z.boolean(),
    "is_hr_admin_edit": z.boolean(),
    "training_trip": z.boolean(),
    "work_trip": z.boolean(),
    "visa_note": z.string(),
    "department_global_id": z.array(z.union([z.number(), z.string()])),
    "sector_id": z.array(z.union([z.number(), z.string()])),
    "message_is_follower": z.boolean(),
    "message_partner_ids": z.array(z.number()),
    "message_channel_ids": z.array(z.any()),
    "message_unread": z.boolean(),
    "message_unread_counter": z.number(),
    "message_needaction": z.boolean(),
    "message_needaction_counter": z.number(),
    "can_submit": z.boolean(),
    "can_refuse": z.boolean(),
    "can_approve": z.boolean(),
    "is_final_step": z.boolean(),
    "is_user": z.boolean(),
    "display_bool": z.boolean(),
    "current_user_id": z.array(z.union([z.number(), z.string()])),
    "is_step_direct_manager": z.boolean(),
    "is_step_dep_manager": z.boolean(),
    "is_step_sector_manager": z.boolean(),
    "is_user_in_group": z.boolean(),
    "display_name": z.string(),
    "__last_update": z.coerce.date(),
});
export type DeputationElement = z.infer<typeof DeputationElementSchema>;
