export type RequestGeneralInfoModel =
  | "holidays"
  | "authorisation"
  | "distance_work"
  | "change_bank_account"
  | "salary_request"
  | "deputation"
  | "overtime_assignment"
  | "overtime_request"
  | "passport_request"
  | "employee_members"
  | "medical_insurance"
  | "purchase_request"
  | "custody"
  | "custody_close"
  | "training_public"
  | "training_request"
  | "change_contract"
