import { paths } from '@lib';
import type { MenuItem } from '@types';
import { Route } from 'next';

export const MenuItems: MenuItem[] = [
  { iconKey: 'Home', label: 'الرئيسية', href: '/' },
  {
    iconKey: 'Citizen',
    label: 'خدمات الموظفين',
    hasSubMenu: true,
    href: '/modal/EmployeeServicesModal' as Route,
    subMenuItems: [
      {
        iconKey: 'Grid',
        label: 'طلباتي',
        href: paths.transactionList.href,
      },
      {
        iconKey: 'PalmTree',
        label: 'الاجازات',
        href: paths.vacations.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'Calendar',
        label: 'الاستئذان',
        href: paths.permissions.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'Map',
        label: 'طلب عمل عن بعد',
        href: paths.remoteWork.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'FolderWithPlus',
        label: 'طلب خطاب الموارد البشرية',
        href: paths.hrLetter.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'UserWithClock',
        label: 'الحضور والانصراف',
        href: paths.attendanceList.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'MultiUsers',
        label: 'حضور الموظفين',
        href: paths.employeeAttendance.href,
        tag: 'hrServices',
      },
      // {
      //   iconKey: 'Fingerprint',
      //   label: 'طلب تبرير حضور أو انصراف',
      //   href: '/',
      //   tag: 'hrServices',
      // },
      { iconKey: 'Timer', label: 'الانتدابات', href: '/', tag: 'hrServices' },
      {
        iconKey: 'ClockTime',
        label: 'العمل الإضافي',
        href: '/',
        tag: 'hrServices',
      },
      {
        iconKey: 'BagWithTimer',
        label: 'طلب تكليف العمل الإضافي',
        href: paths.overtimeAssignment.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'MultiCheck',
        label: 'طلب تأكيد العمل الإضافي',
        href: paths.overtimeConfirm.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'Shield',
        label: 'طلب تأمين طبي',
        href: paths.medicalInsurance.href,
      },
      {
        iconKey: 'UserDetails',
        label: 'طلب تغيير الحساب البنكي',
        href: '/request/bank-account-change',
        tag: 'hrServices',
      },
      {
        iconKey: 'SingleUser',
        label: 'طلب تحديث أفراد الأسرة',
        href: paths.employeeMembers.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'SingleUserWithSquare',
        label: 'طلب تحديث بيانات الجواز',
        href: paths.passports.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'ChartWithArrow',
        label: 'تقييم فترة التجربة',
        href: paths.trialPeriod.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'Arrows',
        label: 'طلب إنهاء الخدمة',
        href: paths.resignation.href,
        tag: 'hrServices',
      },
      {
        iconKey: 'Bag',
        label: 'طلبات التوظيف',
        href: paths.jobApplications.href,
        tag: 'organizationalDevelopment',
      },
      { iconKey: 'Laptop', label: 'طلبات التدريب', href: '/', tag: 'training' },
      {
        iconKey: 'UsersGroup',
        label: 'التدريب الجماعي',
        href: paths.internalCoursesList.href,
        tag: 'training',
      },
      {
        iconKey: 'Flag',
        label: 'ترشيحاتي',
        href: paths.recommendation.href,
        tag: 'training',
      },
      {
        iconKey: 'DoubleSquare',
        label: 'تخطيط الأداء',
        href: '/',
        tag: 'jobPerformance',
      },
      {
        iconKey: 'Telescope',
        label: 'متابعة الأداء',
        href: '/',
        tag: 'jobPerformance',
      },
      {
        iconKey: 'Evaluation',
        label: 'تقييم الأداء',
        href: '/',
        tag: 'jobPerformance',
      },
      {
        iconKey: 'UserWithChart',
        label: 'الترقيات',
        href: '/',
        tag: 'jobPerformance',
      },
      {
        iconKey: 'Circle',
        label: 'المكافآت والعلاوات',
        href: '/',
        tag: 'jobPerformance',
      },
      {
        iconKey: 'List',
        label: 'طلبات المرافق والخدمات والادارية',
        href: '/',
        tag: 'facilitiesServices',
      },
      {
        iconKey: 'Dollar',
        label: 'طلب استعاضة / اقفال عهدة',
        href: paths.replacementCovenant.href,
        tag: 'finance',
      },
      {
        iconKey: 'UserWithShield',
        label: 'طلب عهدة',
        href: paths.custody.href,
        tag: 'finance',
      },
      {
        iconKey: 'Star',
        label: 'تقييم أداء المتعاقدين',
        href: paths.supplierEvaluation.href,
        tag: 'purchases',
      },
      {
        iconKey: 'DashedCircle',
        label: 'طلب شراء',
        href: paths.purchase.href,
        tag: 'purchases',
      },
      {
        iconKey: 'DetailFile',
        label: 'طلب تغيير تعميد / عقد',
        href: '/',
        tag: 'purchases',
      },
      {
        iconKey: 'Cart',
        label: 'طلب إضافة منتجات',
        href: '/',
        tag: 'purchases',
      },
      {
        iconKey: 'EmptyFile',
        label: 'طلب إصدار / تعديل وثيقة',
        href: paths.workDocument.href,
        tag: 'institutionalDiscrimination',
      },
    ],
  },
  {
    iconKey: 'InternalSystems',
    label: 'الأنظمة الداخلية',
    hasSubMenu: true,
    href: '/modal/InternalSystemsModal' as Route,
    subMenuItems: [
      {
        iconKey: 'Info',
        label: 'مركز الطلبات والدعم',
        href: paths.tickets.href,
      },
      {
        iconKey: 'Info',
        label: 'ادارة علاقات العملاء',
        href: paths.crm.href,
      },
      { iconKey: 'Users', label: 'سهل +', href: paths.sahlPlus.href },
      {
        iconKey: 'List',
        label: 'نظام ادارة المهام',
        href: paths.taskManagement.href,
      },
      {
        iconKey: 'Chart',
        label: 'الأداء المالي',
        href: paths.financePerformance.href,
      },
      {
        iconKey: 'Indicator',
        label: 'مؤشرات وبيانات المدفوعات',
        href: paths.paymentsIndicators.href,
      },
      {
        iconKey: 'Files',
        label: 'نظام ادارة الملفات (ايثاق)',
        href: paths.ethaq.href,
      },
      { iconKey: 'Board', label: 'نظام ادارة المشاريع', href: paths.pmo.href },
      {
        iconKey: 'FileWithRightArrow',
        label: 'نظام المحفوظات',
        href: paths.mahfouzat.href,
      },
      { iconKey: 'Lamp', label: 'معمل ابتكار الخدمات', href: paths.lab.href },
      {
        iconKey: 'Cylinder',
        label: 'مركز المعلومات',
        href: paths.informationCenter.href,
      },
      {
        iconKey: 'Key',
        label: 'استعادة كلمة المرور',
        href: paths.resetPassword.href,
      },
      { iconKey: 'Phone', label: 'الهاتف الشبكي', href: paths.phone.href },
      { iconKey: 'Printer', label: 'رمز الطابعة', href: paths.printer.href },
    ],
  },
  {
    iconKey: 'News',
    label: 'الأخبار والإعلانات',
    href: paths.newsList.href,
    // subMenuItems: [
    //   { iconKey: 'Save', label: 'الاخبار', href: '/' },
    //   { iconKey: 'BookAlt', label: 'اعلانات داخلية', href: '/' },
    //   { iconKey: 'T', label: 'عائلة منشآت', href: '/' },
    // ],
  },
  {
    iconKey: 'Search',
    label: 'البحث عن موظف',
    href: paths.searchEmployee.href,
  },
  { iconKey: 'Surveys', label: 'الاستبيانات', href: paths.surveys.href },
  { iconKey: 'Balance', label: 'اللوائح والأنظمة', href: paths.rules.href },
  {
    iconKey: 'Book',
    label: 'مكتبة الجودة الالكترونية',
    href: paths.qualityLibrary.href,
  },
  {
    iconKey: 'File',
    label: 'الإبلاغ عن المخالفات',
    href: paths.reportViolations.href,
  },
  {
    iconKey: 'Mobile',
    label: 'لوحة بيانات الموارد البشرية',
    href: paths.dashboard.href,
  },
  {
    iconKey: 'DownloadApp',
    label: '',
    href: paths.employeeApplication.href,
  },
];
