import {
  ArrowsIcon,
  BagIcon,
  BagWithTimerIcon,
  BalanceIcon,
  BoardIcon,
  BookAltIcon,
  BookIcon,
  BoxIcon,
  BuckleIcon,
  CalendarIcon,
  CartIcon,
  ChartIcon,
  ChartWithArrowIcon,
  CircleIcon,
  CircleSystem1Icon,
  CircleSystem2Icon,
  CircleSystemIcon,
  ClockTimeIcon,
  CylinderIcon,
  DashedCircleIcon,
  DetailFileIcon,
  DollarIcon,
  DoubleSquareIcon,
  DownloadAppIcon,
  EmptyFileIcon,
  EvaluationIcon,
  FileIcon,
  FilesIcon,
  FileWithRightArrowIcon,
  FingerprintIcon,
  FlagIcon,
  FolderWithPlusIcon,
  GridIcon,
  Home1Icon,
  Home2Icon,
  HomeIcon,
  IndicatorIcon,
  InfoIcon,
  KeyIcon,
  LampIcon,
  LaptopIcon,
  ListIcon,
  MapIcon,
  MobileIcon,
  MultiCheckIcon,
  MultiUsersIcon,
  News1Icon,
  News2Icon,
  NewsIcon,
  PalmTreeIcon,
  PhoneIcon,
  PrinterIcon,
  ProfileReviewIcon,
  SaveIcon,
  SearchAltIcon,
  ShieldIcon,
  SingleUserIcon,
  SingleUserWithSquareIcon,
  StarIcon,
  SurveyIcon,
  TelescopeIcon,
  TIcon,
  TimerIcon,
  UserDetailsIcon,
  UserFolderIcon,
  UserIcon,
  Users1Icon,
  Users2Icon,
  UsersGroupIcon,
  UsersIcon,
  UserWithChartIcon,
  UserWithClockIcon,
  UserWithShieldIcon,
} from "@icons"

export const SidebarIcons = {
  Home: <HomeIcon />,
  Home1: <Home1Icon />,
  Home2: <Home2Icon />,
  Citizen: <UserFolderIcon />,
  Citizen1: <Users1Icon />,
  Citizen2: <Users2Icon />,
  InternalSystems: <CircleSystemIcon />,
  InternalSystems1: <CircleSystem1Icon />,
  InternalSystems2: <CircleSystem2Icon />,
  News: <NewsIcon />,
  News1: <News1Icon />,
  News2: <News2Icon />,
  Search: <SearchAltIcon />,
  Surveys: <SurveyIcon />,
  Balance: <BalanceIcon />,
  Book: <BookIcon />,
  BookAlt: <BookAltIcon />,
  BagWithTimer: <BagWithTimerIcon width={30} height={30} />,
  ClockTime: <ClockTimeIcon width={30} height={30} />,
  File: <FileIcon />,
  Mobile: <MobileIcon />,
  User: <UserIcon className="fill-[#88D0EC]" />,
  Info: <InfoIcon width={30} height={30} />,
  Board: <BoardIcon width={30} height={30} />,
  Buckle: <BuckleIcon />,
  Chart: <ChartIcon width={30} height={30} />,
  Cylinder: <CylinderIcon width={30} height={30} />,
  Files: <FilesIcon width={30} height={30} />,
  FileWithRightArrow: <FileWithRightArrowIcon width={30} height={30} />,
  Indicator: <IndicatorIcon width={30} height={30} />,
  Key: <KeyIcon width={30} height={30} />,
  List: <ListIcon width={30} height={30} />,
  Phone: <PhoneIcon width={30} height={30} />,
  Printer: <PrinterIcon width={30} height={30} className="fill-primary" />,
  Shield: <ShieldIcon width={30} height={30} />,
  UserFolder: <UserFolderIcon />,
  Users: <UsersIcon width={30} height={30} />,
  MultiUsers: <MultiUsersIcon width={30} height={30} />,
  Box: <BoxIcon />,
  PalmTree: <PalmTreeIcon width={30} height={30} />,
  Calendar: <CalendarIcon width={30} height={30} />,
  Map: <MapIcon width={30} height={30} />,
  Timer: <TimerIcon width={30} height={30} />,
  UserWithClock: <UserWithClockIcon width={30} height={30} />,
  Fingerprint: <FingerprintIcon width={30} height={30} />,
  FolderWithPlus: <FolderWithPlusIcon width={30} height={30} />,
  UserDetails: <UserDetailsIcon width={30} height={30} />,
  DashedCircle: <DashedCircleIcon width={30} height={30} />,
  Dollar: <DollarIcon width={30} height={30} />,
  ChartWithArrow: <ChartWithArrowIcon width={30} height={30} />,
  Bag: <BagIcon width={30} height={30} />,
  Save: <SaveIcon />,
  T: <TIcon />,
  MultiCheck: <MultiCheckIcon width={30} height={30} />,
  SingleUser: <SingleUserIcon width={30} height={30} />,
  SingleUserWithSquare: <SingleUserWithSquareIcon width={30} height={30} />,
  Arrows: <ArrowsIcon width={30} height={30} />,
  Laptop: <LaptopIcon width={30} height={30} />,
  UsersGroup: <UsersGroupIcon width={30} height={30} />,
  Flag: <FlagIcon width={30} height={30} />,
  DoubleSquare: <DoubleSquareIcon width={30} height={30} />,
  Telescope: <TelescopeIcon width={30} height={30} />,
  Evaluation: <EvaluationIcon width={30} height={30} />,
  UserWithChart: <UserWithChartIcon width={30} height={30} />,
  Circle: <CircleIcon width={30} height={30} />,
  UserWithShield: <UserWithShieldIcon width={30} height={30} />,
  Star: <StarIcon width={30} height={30} />,
  DetailFile: <DetailFileIcon width={30} height={30} />,
  Cart: <CartIcon width={30} height={30} />,
  EmptyFile: <EmptyFileIcon width={30} height={30} />,
  Lamp: <LampIcon width={30} height={30} />,
  Grid: <GridIcon width={30} height={30} />,
  DownloadApp: <DownloadAppIcon width={30} height={30} />,
  ProfileReview: <ProfileReviewIcon width={30} height={30} />,
} as const
