import * as z from "zod"

export const PassportRequestSchema = z.object({
  id: z.any(),
  name: z.any(),
  date: z.any(),
  employee_id: z.any(),
  state: z.any(),
  actual_passport: z.any(),
  new_passport: z.any(),
  passport_end_date: z.any(),
  passport_image: z.any(),
  active: z.any(),
  website_message_ids: z.any(),
  message_follower_ids: z.any(),
  message_ids: z.any(),
  message_last_post: z.any(),
  create_uid: z.any(),
  create_date: z.any(),
  write_uid: z.any(),
  write_date: z.any(),
  message_is_follower: z.any(),
  message_partner_ids: z.any(),
  message_channel_ids: z.any(),
  message_unread: z.any(),
  message_unread_counter: z.any(),
  message_needaction: z.any(),
  message_needaction_counter: z.any(),
  display_name: z.any(),
  __last_update: z.any(),
})
export type PassportRequest = z.infer<typeof PassportRequestSchema>

// export const PassportRequestSchema = z.object({
//   id: z.number(),
//   name: z.string(),
//   date: z.string(),
//   employee_id: z.array(z.union([z.number(), z.string()])),
//   state: z.string(),
//   actual_passport: z.boolean(),
//   new_passport: z.string(),
//   passport_end_date: z.string(),
//   passport_image: z.string(),
//   active: z.boolean(),
//   website_message_ids: z.array(z.any()),
//   message_follower_ids: z.array(z.number()),
//   message_ids: z.array(z.number()),
//   message_last_post: z.boolean(),
//   create_uid: z.array(z.union([z.number(), z.string()])),
//   create_date: z.coerce.date(),
//   write_uid: z.array(z.union([z.number(), z.string()])),
//   write_date: z.coerce.date(),
//   message_is_follower: z.boolean(),
//   message_partner_ids: z.array(z.number()),
//   message_channel_ids: z.array(z.any()),
//   message_unread: z.boolean(),
//   message_unread_counter: z.number(),
//   message_needaction: z.boolean(),
//   message_needaction_counter: z.number(),
//   display_name: z.string(),
//   __last_update: z.coerce.date(),
// })
// export type PassportRequest = z.infer<typeof PassportRequestSchema>
