import {
  HomeIcon,
  FileIcon,
  UserFolderIcon,
  CircleSystemIcon,
  NewsIcon,
  SearchAltIcon,
  SurveyIcon,
  MobileIcon,
  UserIcon,
  BookIcon,
  InfoIcon,
  BalanceIcon,
  BoardIcon,
  BuckleIcon,
  ChartIcon,
  CylinderIcon,
  FilesIcon,
  FileWithRightArrowIcon,
  IndicatorIcon,
  KeyIcon,
  ListIcon,
  PrinterIcon,
  ShieldIcon,
  UsersIcon,
  PhoneIcon,
  BookAltIcon,
  BoxIcon,
  PalmTreeIcon,
  CalendarIcon,
  MapIcon,
  TimerIcon,
  UserWithClockIcon,
  FingerprintIcon,
  FolderWithPlusIcon,
  UserDetailsIcon,
  DashedCircleIcon,
  DollarIcon,
  ChartWithArrowIcon,
  BagIcon,
  SaveIcon,
  TIcon,
} from '@icons';

export const SidebarIcons = {
  Home: <HomeIcon />,
  Citizen: <UserFolderIcon />,
  InternalSystems: <CircleSystemIcon />,
  News: <NewsIcon />,
  Search: <SearchAltIcon />,
  Surveys: <SurveyIcon />,
  Balance: <BalanceIcon />,
  Book: <BookIcon />,
  BookAlt: <BookAltIcon />,
  File: <FileIcon />,
  Mobile: <MobileIcon />,
  User: <UserIcon className='fill-[#88D0EC]' />,
  Info: <InfoIcon />,
  Board: <BoardIcon />,
  Buckle: <BuckleIcon />,
  Chart: <ChartIcon />,
  Cylinder: <CylinderIcon />,
  Files: <FilesIcon />,
  FileWithRightArrow: <FileWithRightArrowIcon />,
  Indicator: <IndicatorIcon />,
  Key: <KeyIcon />,
  List: <ListIcon />,
  Phone: <PhoneIcon />,
  Printer: <PrinterIcon />,
  Shield: <ShieldIcon />,
  UserFolder: <UserFolderIcon />,
  Users: <UsersIcon />,
  Box: <BoxIcon />,
  PalmTree: <PalmTreeIcon />,
  Calendar: <CalendarIcon />,
  Map: <MapIcon />,
  Timer: <TimerIcon />,
  UserWithClock: <UserWithClockIcon />,
  Fingerprint: <FingerprintIcon />,
  FolderWithPlus: <FolderWithPlusIcon />,
  UserDetails: <UserDetailsIcon />,
  DashedCircle: <DashedCircleIcon />,
  Dollar: <DollarIcon />,
  ChartWithArrow: <ChartWithArrowIcon />,
  Bag: <BagIcon />,
  Save: <SaveIcon />,
  T: <TIcon />,
} as const;

export type IconKey = keyof typeof SidebarIcons;
