import * as z from "zod";

export const RemoteWorkElementSchema = z.object({
    "id": z.any(),
    "employee_id": z.any(),
    "number": z.any(),
    "department_id": z.any(),
    "job_id": z.any(),
    "grade_id": z.any(),
    "type_id": z.any(),
    "degree_id": z.any(),
    "name": z.any(),
    "date_from": z.any(),
    "date_to": z.any(),
    "duration": z.any(),
    "state": z.any(),
    "reason": z.any(),
    "active": z.any(),
    "description": z.any(),
    "is_reviewed_approved": z.any(),
    "note": z.any(),
    "is_token_updated": z.any(),
    "res_model": z.any(),
    "is_from_mobile": z.any(),
    "mobile_approvals_ids": z.any(),
    "message_follower_ids": z.any(),
    "message_ids": z.any(),
    "message_last_post": z.any(),
    "website_message_ids": z.any(),
    "create_uid": z.any(),
    "create_date": z.any(),
    "write_uid": z.any(),
    "write_date": z.any(),
    "is_direct_manager": z.any(),
    "current_stock": z.any(),
    "department_global_id": z.any(),
    "sector_id": z.any(),
    "message_is_follower": z.any(),
    "message_partner_ids": z.any(),
    "message_channel_ids": z.any(),
    "message_unread": z.any(),
    "message_unread_counter": z.any(),
    "message_needaction": z.any(),
    "message_needaction_counter": z.any(),
    "display_name": z.any(),
    "__last_update": z.any(),
});
export type RemoteWorkElement = z.infer<typeof RemoteWorkElementSchema>;


// export const RemoteWorkElementSchema = z.object({
//     "id": z.number(),
//     "employee_id": z.array(z.union([z.string(), z.number()])),
//     "number": z.string(),
//     "department_id": z.array(z.union([z.number(), z.string()])),
//     "job_id": z.array(z.union([z.string(), z.number()])),
//     "grade_id": z.array(z.union([z.string(), z.number()])),
//     "type_id": z.array(z.union([z.string(), z.number()])),
//     "degree_id": z.array(z.union([z.number(), z.string()])),
//     "name": z.string(),
//     "date_from": z.string(),
//     "date_to": z.string(),
//     "duration": z.number(),
//     "state": z.string(),
//     "reason": z.boolean(),
//     "active": z.boolean(),
//     "description": z.string(),
//     "is_reviewed_approved": z.boolean(),
//     "note": z.union([z.boolean(), z.string()]),
//     "is_token_updated": z.boolean(),
//     "res_model": z.string(),
//     "is_from_mobile": z.boolean(),
//     "mobile_approvals_ids": z.array(z.number()),
//     "message_follower_ids": z.array(z.number()),
//     "message_ids": z.array(z.number()),
//     "message_last_post": z.boolean(),
//     "website_message_ids": z.array(z.any()),
//     "create_uid": z.array(z.union([z.string(), z.number()])),
//     "create_date": z.coerce.date(),
//     "write_uid": z.array(z.union([z.string(), z.number()])),
//     "write_date": z.coerce.date(),
//     "is_direct_manager": z.boolean(),
//     "current_stock": z.number(),
//     "department_global_id": z.array(z.union([z.string(), z.number()])),
//     "sector_id": z.array(z.union([z.string(), z.number()])),
//     "message_is_follower": z.boolean(),
//     "message_partner_ids": z.array(z.number()),
//     "message_channel_ids": z.array(z.any()),
//     "message_unread": z.boolean(),
//     "message_unread_counter": z.number(),
//     "message_needaction": z.boolean(),
//     "message_needaction_counter": z.number(),
//     "display_name": z.string(),
//     "__last_update": z.coerce.date(),
// });
// export type RemoteWorkElement = z.infer<typeof RemoteWorkElementSchema>;
