import * as z from "zod";


export const RemoteWorkElementSchema = z.object({
    "id": z.number(),
    "employee_id": z.array(z.union([z.string(), z.number()])),
    "number": z.string(),
    "department_id": z.array(z.union([z.number(), z.string()])),
    "job_id": z.array(z.union([z.string(), z.number()])),
    "grade_id": z.array(z.union([z.string(), z.number()])),
    "type_id": z.array(z.union([z.string(), z.number()])),
    "degree_id": z.array(z.union([z.number(), z.string()])),
    "name": z.string(),
    "date_from": z.string(),
    "date_to": z.string(),
    "duration": z.number(),
    "state": z.string(),
    "reason": z.boolean(),
    "active": z.boolean(),
    "description": z.string(),
    "is_reviewed_approved": z.boolean(),
    "note": z.union([z.boolean(), z.string()]),
    "is_token_updated": z.boolean(),
    "res_model": z.string(),
    "is_from_mobile": z.boolean(),
    "mobile_approvals_ids": z.array(z.number()),
    "message_follower_ids": z.array(z.number()),
    "message_ids": z.array(z.number()),
    "message_last_post": z.boolean(),
    "website_message_ids": z.array(z.any()),
    "create_uid": z.array(z.union([z.string(), z.number()])),
    "create_date": z.coerce.date(),
    "write_uid": z.array(z.union([z.string(), z.number()])),
    "write_date": z.coerce.date(),
    "is_direct_manager": z.boolean(),
    "current_stock": z.number(),
    "department_global_id": z.array(z.union([z.string(), z.number()])),
    "sector_id": z.array(z.union([z.string(), z.number()])),
    "message_is_follower": z.boolean(),
    "message_partner_ids": z.array(z.number()),
    "message_channel_ids": z.array(z.any()),
    "message_unread": z.boolean(),
    "message_unread_counter": z.number(),
    "message_needaction": z.boolean(),
    "message_needaction_counter": z.number(),
    "display_name": z.string(),
    "__last_update": z.coerce.date(),
});
export type RemoteWorkElement = z.infer<typeof RemoteWorkElementSchema>;
