import * as z from "zod"

export const HrTrainingSchema = z.object({
  id: z.any(),
  name: z.any(),
  number: z.any(),
  date: z.any(),
  date_from: z.any(),
  date_to: z.any(),
  number_of_days: z.any(),
  place: z.any(),
  number_place: z.any(),
  application_ids: z.any(),
  state: z.any(),
  reason_to_cancel: z.any(),
  training_center: z.any(),
  training_center_id: z.any(),
  partner_ids: z.any(),
  type: z.any(),
  amount: z.any(),
  country_id: z.any(),
  programme_training: z.any(),
  published: z.any(),
  attachment_ids: z.any(),
  display_button_candidat_course: z.any(),
  city: z.any(),
  currency_id: z.any(),
  public_ids: z.any(),
  refuse_reason: z.any(),
  active: z.any(),
  type_training_activity: z.any(),
  create_employee_id: z.any(),
  website_message_ids: z.any(),
  message_follower_ids: z.any(),
  message_ids: z.any(),
  message_last_post: z.any(),
  create_uid: z.any(),
  create_date: z.any(),
  write_uid: z.any(),
  write_date: z.any(),
  number_participant: z.any(),
  display_button: z.any(),
  message_is_follower: z.any(),
  message_partner_ids: z.any(),
  message_channel_ids: z.any(),
  message_unread: z.any(),
  message_unread_counter: z.any(),
  message_needaction: z.any(),
  message_needaction_counter: z.any(),
  display_name: z.any(),
  __last_update: z.any(),
})

export type HrTraining = z.infer<typeof HrTrainingSchema>
