export { AdditionalInfoSection } from "./AdditionalInfoSection"
export { AttachmentsSection } from "./AttachmentsSection"
export { DateDurationSection } from "./DateDurationSection"
export { ExtendedTrainingSection } from "./ExtendedTrainingSection"
export { TrainingCenterSection } from "./TrainingCenterSection"
export { TrainingDetailsSection } from "./TrainingDetailsSection"
export { TrainingLocationSection } from "./TrainingLocationSection"
export { TrainingTypeSection } from "./TrainingTypeSection"
