import * as z from "zod";

export const HrTrainingDivisionIdSchema = z.object({
    "id": z.number(),
    "hr_training_request_id": z.array(z.union([z.number(), z.string()])),
    "date_from": z.string(),
    "date_to": z.string(),
    "duration": z.number(),
    "travel_days_setting": z.string(),
    "date_from_travel": z.string(),
    "date_to_travel": z.string(),
    "direct_action_id": z.boolean(),
    "attachment_ids": z.array(z.any()),
    "create_uid": z.array(z.union([z.number(), z.string()])),
    "create_date": z.coerce.date(),
    "write_uid": z.array(z.union([z.number(), z.string()])),
    "write_date": z.coerce.date(),
    "travel_day": z.string(),
    "display_travel_days_setting": z.boolean(),
    "amount_training": z.number(),
    "direct_action_state": z.boolean(),
    "sequence_number": z.number(),
    "display_name": z.string(),
    "__last_update": z.coerce.date(),
});
export type HrTrainingDivisionId = z.infer<typeof HrTrainingDivisionIdSchema>;

export const TrainingElementSchema = z.object({
    "id": z.number(),
    "name": z.string(),
    "number": z.string(),
    "date": z.string(),
    "date_from": z.union([z.boolean(), z.string()]),
    "date_to": z.union([z.boolean(), z.string()]),
    "duration": z.number(),
    "training_center": z.union([z.boolean(), z.string()]),
    "training_center_id": z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
    "type": z.string(),
    "job_id": z.boolean(),
    "type_id": z.array(z.union([z.string(), z.number()])),
    "department_id": z.array(z.union([z.number(), z.string()])),
    "grade_id": z.array(z.union([z.string(), z.number()])),
    "degree_id": z.array(z.union([z.number(), z.string()])),
    "amount": z.number(),
    "attachment_ids": z.array(z.number()),
    "attachment_invoice_ids": z.array(z.any()),
    "country_id": z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
    "city": z.union([z.boolean(), z.string()]),
    "employee_city_id": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
    "city_id": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
    "programme_session": z.string(),
    "state": z.string(),
    "employee_id": z.array(z.union([z.string(), z.number()])),
    "refuse_reason": z.union([z.boolean(), z.string()]),
    "currency_id": z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
    "the_availability": z.string(),
    "travel_days": z.union([z.boolean(), z.string()]),
    "deputation_allowance": z.number(),
    "ticket_amount": z.number(),
    "car_amount": z.number(),
    "ticket_reserved": z.boolean(),
    "expected_date": z.boolean(),
    "substitute_employee_id": z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
    "active": z.boolean(),
    "token": z.boolean(),
    "is_need_visa": z.boolean(),
    "flight_class": z.string(),
    "flight_number": z.boolean(),
    "flight_date": z.boolean(),
    "flight_air": z.boolean(),
    "ticket_cost": z.number(),
    "itinerary": z.boolean(),
    "reservation_mail_sent": z.boolean(),
    "direct_action_number": z.boolean(),
    "direct_action_date": z.boolean(),
    "direct_action_state": z.boolean(),
    "has_direct_action": z.boolean(),
    "direct_action_attachment_ids": z.array(z.any()),
    "date_from_travel": z.union([z.boolean(), z.string()]),
    "date_to_travel": z.union([z.boolean(), z.string()]),
    "is_long_duration": z.boolean(),
    "is_short_internal": z.boolean(),
    "travel_days_setting": z.union([z.boolean(), z.string()]),
    "date_confirm": z.boolean(),
    "training_type_id": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
    "is_test": z.boolean(),
    "is_training": z.boolean(),
    "is_membership": z.boolean(),
    "is_studying_subjects": z.boolean(),
    "is_other_centers": z.boolean(),
    "training_center_name": z.union([z.boolean(), z.string()]),
    "return_reason": z.boolean(),
    "training_return_reason": z.boolean(),
    "degree": z.boolean(),
    "extended_training": z.boolean(),
    "hr_training_division_ids": z.union([z.array(HrTrainingDivisionIdSchema), z.null()]),
    "travel_data_line_ids": z.array(z.any()),
    "financial_type": z.string(),
    "state_direct_action": z.string(),
    "direct_action_extended_training_ids": z.array(z.any()),
    "deputation_request_id": z.boolean(),
    "res_model": z.string(),
    "is_from_mobile": z.boolean(),
    "mobile_approvals_ids": z.array(z.any()),
    "website_message_ids": z.array(z.any()),
    "message_follower_ids": z.array(z.number()),
    "message_ids": z.array(z.number()),
    "message_last_post": z.boolean(),
    "create_uid": z.array(z.union([z.string(), z.number()])),
    "create_date": z.coerce.date(),
    "write_uid": z.array(z.union([z.string(), z.number()])),
    "write_date": z.coerce.date(),
    "partner_ids": z.array(z.number()),
    "is_direct_manager": z.boolean(),
    "amount_training": z.number(),
    "total": z.number(),
    "display_button_direct_action": z.boolean(),
    "display_button_reserve_ticket": z.boolean(),
    "display_button_send": z.boolean(),
    "is_sector_manager": z.boolean(),
    "display_travel_days_setting": z.boolean(),
    "display_travel_dates": z.boolean(),
    "sa_amount": z.number(),
    "display_employee_action": z.boolean(),
    "display_professional_certificate_options": z.boolean(),
    "check_training_date_to": z.boolean(),
    "show_button_order_accept": z.boolean(),
    "count_direct_action_extended_training": z.number(),
    "department_global_id": z.array(z.union([z.string(), z.number()])),
    "sector_id": z.array(z.union([z.string(), z.number()])),
    "message_is_follower": z.boolean(),
    "message_partner_ids": z.array(z.number()),
    "message_channel_ids": z.array(z.any()),
    "message_unread": z.boolean(),
    "message_unread_counter": z.number(),
    "message_needaction": z.boolean(),
    "message_needaction_counter": z.number(),
    "display_name": z.string(),
    "__last_update": z.coerce.date(),
});
export type TrainingElement = z.infer<typeof TrainingElementSchema>;
