import * as z from "zod"

export const TrainingElementSchema = z.object({
  id: z.any(),
  name: z.any(),
  number: z.any(),
  date: z.any(),
  date_from: z.any(),
  date_to: z.any(),
  duration: z.any(),
  training_center: z.any(),
  training_center_id: z.any(),
  type: z.any(),
  job_id: z.any(),
  type_id: z.any(),
  department_id: z.any(),
  grade_id: z.any(),
  degree_id: z.any(),
  amount: z.any(),
  attachment_ids: z.any(),
  attachment_invoice_ids: z.any(),
  country_id: z.any(),
  city: z.any(),
  employee_city_id: z.any(),
  city_id: z.any(),
  programme_session: z.any(),
  state: z.any(),
  employee_id: z.any(),
  refuse_reason: z.any(),
  currency_id: z.any(),
  the_availability: z.any(),
  travel_days: z.any(),
  deputation_allowance: z.any(),
  ticket_amount: z.any(),
  car_amount: z.any(),
  ticket_reserved: z.any(),
  expected_date: z.any(),
  substitute_employee_id: z.any(),
  active: z.any(),
  token: z.any(),
  is_need_visa: z.any(),
  flight_class: z.any(),
  flight_number: z.any(),
  flight_date: z.any(),
  flight_air: z.any(),
  ticket_cost: z.any(),
  itinerary: z.any(),
  reservation_mail_sent: z.any(),
  direct_action_number: z.any(),
  direct_action_date: z.any(),
  direct_action_state: z.any(),
  has_direct_action: z.any(),
  direct_action_attachment_ids: z.any(),
  date_from_travel: z.any(),
  date_to_travel: z.any(),
  is_long_duration: z.any(),
  is_short_internal: z.any(),
  travel_days_setting: z.any(),
  date_confirm: z.any(),
  training_type_id: z.any(),
  is_test: z.any(),
  is_training: z.any(),
  is_membership: z.any(),
  is_studying_subjects: z.any(),
  is_other_centers: z.any(),
  training_center_name: z.any(),
  return_reason: z.any(),
  training_return_reason: z.any(),
  degree: z.any(),
  extended_training: z.any(),
  hr_training_division_ids: z.any(),
  travel_data_line_ids: z.any(),
  financial_type: z.any(),
  state_direct_action: z.any(),
  direct_action_extended_training_ids: z.any(),
  deputation_request_id: z.any(),
  res_model: z.any(),
  is_from_mobile: z.any(),
  mobile_approvals_ids: z.any(),
  website_message_ids: z.any(),
  message_follower_ids: z.any(),
  message_ids: z.any(),
  message_last_post: z.any(),
  create_uid: z.any(),
  create_date: z.any(),
  write_uid: z.any(),
  write_date: z.any(),
  partner_ids: z.any(),
  is_direct_manager: z.any(),
  amount_training: z.any(),
  total: z.any(),
  display_button_direct_action: z.any(),
  display_button_reserve_ticket: z.any(),
  display_button_send: z.any(),
  is_sector_manager: z.any(),
  display_travel_days_setting: z.any(),
  display_travel_dates: z.any(),
  sa_amount: z.any(),
  display_employee_action: z.any(),
  display_professional_certificate_options: z.any(),
  check_training_date_to: z.any(),
  show_button_order_accept: z.any(),
  count_direct_action_extended_training: z.any(),
  department_global_id: z.any(),
  sector_id: z.any(),
  message_is_follower: z.any(),
  message_partner_ids: z.any(),
  message_channel_ids: z.any(),
  message_unread: z.any(),
  message_unread_counter: z.any(),
  message_needaction: z.any(),
  message_needaction_counter: z.any(),
  display_name: z.any(),
  __last_update: z.any(),
  number_of_days: z.any(),
})
export type TrainingElement = z.infer<typeof TrainingElementSchema>

// export const HrTrainingDivisionIdSchema = z.object({
//     "id": z.number(),
//     "hr_training_request_id": z.array(z.union([z.number(), z.string()])),
//     "date_from": z.string(),
//     "date_to": z.string(),
//     "duration": z.number(),
//     "travel_days_setting": z.string(),
//     "date_from_travel": z.string(),
//     "date_to_travel": z.string(),
//     "direct_action_id": z.boolean(),
//     "attachment_ids": z.array(z.any()),
//     "create_uid": z.array(z.union([z.number(), z.string()])),
//     "create_date": z.coerce.date(),
//     "write_uid": z.array(z.union([z.number(), z.string()])),
//     "write_date": z.coerce.date(),
//     "travel_day": z.string(),
//     "display_travel_days_setting": z.boolean(),
//     "amount_training": z.number(),
//     "direct_action_state": z.boolean(),
//     "sequence_number": z.number(),
//     "display_name": z.string(),
//     "__last_update": z.coerce.date(),
// });
// export type HrTrainingDivisionId = z.infer<typeof HrTrainingDivisionIdSchema>;

// export const TrainingElementSchema = z.object({
//     "id": z.number(),
//     "name": z.string(),
//     "number": z.string(),
//     "date": z.string(),
//     "date_from": z.union([z.boolean(), z.string()]),
//     "date_to": z.union([z.boolean(), z.string()]),
//     "duration": z.number(),
//     "training_center": z.union([z.boolean(), z.string()]),
//     "training_center_id": z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
//     "type": z.string(),
//     "job_id": z.boolean(),
//     "type_id": z.array(z.union([z.string(), z.number()])),
//     "department_id": z.array(z.union([z.number(), z.string()])),
//     "grade_id": z.array(z.union([z.string(), z.number()])),
//     "degree_id": z.array(z.union([z.number(), z.string()])),
//     "amount": z.number(),
//     "attachment_ids": z.array(z.number()),
//     "attachment_invoice_ids": z.array(z.any()),
//     "country_id": z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
//     "city": z.union([z.boolean(), z.string()]),
//     "employee_city_id": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
//     "city_id": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
//     "programme_session": z.string(),
//     "state": z.string(),
//     "employee_id": z.array(z.union([z.string(), z.number()])),
//     "refuse_reason": z.union([z.boolean(), z.string()]),
//     "currency_id": z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
//     "the_availability": z.string(),
//     "travel_days": z.union([z.boolean(), z.string()]),
//     "deputation_allowance": z.number(),
//     "ticket_amount": z.number(),
//     "car_amount": z.number(),
//     "ticket_reserved": z.boolean(),
//     "expected_date": z.boolean(),
//     "substitute_employee_id": z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
//     "active": z.boolean(),
//     "token": z.boolean(),
//     "is_need_visa": z.boolean(),
//     "flight_class": z.string(),
//     "flight_number": z.boolean(),
//     "flight_date": z.boolean(),
//     "flight_air": z.boolean(),
//     "ticket_cost": z.number(),
//     "itinerary": z.boolean(),
//     "reservation_mail_sent": z.boolean(),
//     "direct_action_number": z.boolean(),
//     "direct_action_date": z.boolean(),
//     "direct_action_state": z.boolean(),
//     "has_direct_action": z.boolean(),
//     "direct_action_attachment_ids": z.array(z.any()),
//     "date_from_travel": z.union([z.boolean(), z.string()]),
//     "date_to_travel": z.union([z.boolean(), z.string()]),
//     "is_long_duration": z.boolean(),
//     "is_short_internal": z.boolean(),
//     "travel_days_setting": z.union([z.boolean(), z.string()]),
//     "date_confirm": z.boolean(),
//     "training_type_id": z.union([z.array(z.union([z.string(), z.number()])), z.boolean()]),
//     "is_test": z.boolean(),
//     "is_training": z.boolean(),
//     "is_membership": z.boolean(),
//     "is_studying_subjects": z.boolean(),
//     "is_other_centers": z.boolean(),
//     "training_center_name": z.union([z.boolean(), z.string()]),
//     "return_reason": z.boolean(),
//     "training_return_reason": z.boolean(),
//     "degree": z.boolean(),
//     "extended_training": z.boolean(),
//     "hr_training_division_ids": z.union([z.array(HrTrainingDivisionIdSchema), z.null()]),
//     "travel_data_line_ids": z.array(z.any()),
//     "financial_type": z.string(),
//     "state_direct_action": z.string(),
//     "direct_action_extended_training_ids": z.array(z.any()),
//     "deputation_request_id": z.boolean(),
//     "res_model": z.string(),
//     "is_from_mobile": z.boolean(),
//     "mobile_approvals_ids": z.array(z.any()),
//     "website_message_ids": z.array(z.any()),
//     "message_follower_ids": z.array(z.number()),
//     "message_ids": z.array(z.number()),
//     "message_last_post": z.boolean(),
//     "create_uid": z.array(z.union([z.string(), z.number()])),
//     "create_date": z.coerce.date(),
//     "write_uid": z.array(z.union([z.string(), z.number()])),
//     "write_date": z.coerce.date(),
//     "partner_ids": z.array(z.number()),
//     "is_direct_manager": z.boolean(),
//     "amount_training": z.number(),
//     "total": z.number(),
//     "display_button_direct_action": z.boolean(),
//     "display_button_reserve_ticket": z.boolean(),
//     "display_button_send": z.boolean(),
//     "is_sector_manager": z.boolean(),
//     "display_travel_days_setting": z.boolean(),
//     "display_travel_dates": z.boolean(),
//     "sa_amount": z.number(),
//     "display_employee_action": z.boolean(),
//     "display_professional_certificate_options": z.boolean(),
//     "check_training_date_to": z.boolean(),
//     "show_button_order_accept": z.boolean(),
//     "count_direct_action_extended_training": z.number(),
//     "department_global_id": z.array(z.union([z.string(), z.number()])),
//     "sector_id": z.array(z.union([z.string(), z.number()])),
//     "message_is_follower": z.boolean(),
//     "message_partner_ids": z.array(z.number()),
//     "message_channel_ids": z.array(z.any()),
//     "message_unread": z.boolean(),
//     "message_unread_counter": z.number(),
//     "message_needaction": z.boolean(),
//     "message_needaction_counter": z.number(),
//     "display_name": z.string(),
//     "__last_update": z.coerce.date(),
// });
// export type TrainingElement = z.infer<typeof TrainingElementSchema>;
