import * as z from "zod"

export const TrainingElementSchema = z.object({
  id: z.any(),
  name: z.any(),
  number: z.any(),
  date: z.any(),
  date_from: z.any(),
  date_to: z.any(),
  number_of_days: z.any(),
  place: z.any(),
  number_place: z.any(),
  application_ids: z.any(),
  state: z.any(),
  reason_to_cancel: z.any(),
  training_center: z.any(),
  training_center_id: z.any(),
  partner_ids: z.any(),
  type: z.any(),
  amount: z.any(),
  country_id: z.any(),
  programme_training: z.any(),
  published: z.any(),
  attachment_ids: z.any(),
  display_button_candidat_course: z.any(),
  city: z.any(),
  currency_id: z.any(),
  public_ids: z.any(),
  refuse_reason: z.any(),
  active: z.any(),
  type_training_activity: z.any(),
  create_employee_id: z.any(),
  website_message_ids: z.any(),
  message_follower_ids: z.any(),
  message_ids: z.any(),
  message_last_post: z.any(),
  create_uid: z.any(),
  create_date: z.any(),
  write_uid: z.any(),
  write_date: z.any(),
  number_participant: z.any(),
  display_button: z.any(),
  message_is_follower: z.any(),
  message_partner_ids: z.any(),
  message_channel_ids: z.any(),
  message_unread: z.any(),
  message_unread_counter: z.any(),
  message_needaction: z.any(),
  message_needaction_counter: z.any(),
  display_name: z.any(),
  __last_update: z.any(),
})
export type TrainingElement = z.infer<typeof TrainingElementSchema>

// export const TrainingElementSchema = z.object({
//   id: z.number(),
//   name: z.string(),
//   number: z.string(),
//   date: z.string(),
//   date_from: z.string(),
//   date_to: z.string(),
//   number_of_days: z.number(),
//   place: z.union([z.array(z.union([z.number(), z.string()])), z.boolean()]),
//   number_place: z.number(),
//   application_ids: z.array(z.any()),
//   state: z.string(),
//   reason_to_cancel: z.boolean(),
//   training_center: z.string(),
//   training_center_id: z.boolean(),
//   partner_ids: z.array(z.number()),
//   type: z.string(),
//   amount: z.number(),
//   country_id: z.union([
//     z.array(z.union([z.number(), z.string()])),
//     z.boolean(),
//   ]),
//   programme_training: z.string(),
//   published: z.boolean(),
//   attachment_ids: z.array(z.number()),
//   display_button_candidat_course: z.boolean(),
//   city: z.union([z.boolean(), z.string()]),
//   currency_id: z.boolean(),
//   public_ids: z.array(z.number()),
//   refuse_reason: z.boolean(),
//   active: z.boolean(),
//   type_training_activity: z.boolean(),
//   create_employee_id: z.array(z.union([z.number(), z.string()])),
//   website_message_ids: z.array(z.any()),
//   message_follower_ids: z.array(z.number()),
//   message_ids: z.array(z.number()),
//   message_last_post: z.boolean(),
//   create_uid: z.array(z.union([z.number(), z.string()])),
//   create_date: z.coerce.date(),
//   write_uid: z.array(z.union([z.number(), z.string()])),
//   write_date: z.coerce.date(),
//   number_participant: z.number(),
//   display_button: z.boolean(),
//   message_is_follower: z.boolean(),
//   message_partner_ids: z.array(z.number()),
//   message_channel_ids: z.array(z.any()),
//   message_unread: z.boolean(),
//   message_unread_counter: z.number(),
//   message_needaction: z.boolean(),
//   message_needaction_counter: z.number(),
//   display_name: z.string(),
//   __last_update: z.coerce.date(),
// })
// export type TrainingElement = z.infer<typeof TrainingElementSchema>
