import * as z from "zod"

export const RecommendationSchema = z.object({
  id: z.any(),
  employee_id: z.any(),
  number: z.any(),
  training_id: z.any(),
  place: z.any(),
  state: z.any(),
  cause: z.any(),
  date: z.any(),
  degree_id: z.any(),
  department_id: z.any(),
  job_id: z.any(),
  date_from: z.any(),
  date_to: z.any(),
  type: z.any(),
  training_center: z.any(),
  number_of_days: z.any(),
  refuse_reason: z.any(),
  active: z.any(),
  message_follower_ids: z.any(),
  message_ids: z.any(),
  message_last_post: z.any(),
  website_message_ids: z.any(),
  create_uid: z.any(),
  create_date: z.any(),
  write_uid: z.any(),
  write_date: z.any(),
  is_direct_manager: z.any(),
  message_is_follower: z.any(),
  message_partner_ids: z.any(),
  message_channel_ids: z.any(),
  message_unread: z.any(),
  message_unread_counter: z.any(),
  message_needaction: z.any(),
  message_needaction_counter: z.any(),
  display_name: z.any(),
  __last_update: z.any(),
})
export type Recommendation = z.infer<typeof RecommendationSchema>

// export const RecommendationSchema = z.object({
//   id: z.number(),
//   employee_id: z.array(z.union([z.number(), z.string()])),
//   number: z.string(),
//   training_id: z.array(z.union([z.number(), z.string()])),
//   place: z.array(z.union([z.number(), z.string()])),
//   state: z.string(),
//   cause: z.boolean(),
//   date: z.string(),
//   degree_id: z.array(z.union([z.number(), z.string()])),
//   department_id: z.array(z.union([z.number(), z.string()])),
//   job_id: z.array(z.union([z.number(), z.string()])),
//   date_from: z.string(),
//   date_to: z.string(),
//   type: z.string(),
//   training_center: z.string(),
//   number_of_days: z.number(),
//   refuse_reason: z.boolean(),
//   active: z.boolean(),
//   message_follower_ids: z.array(z.number()),
//   message_ids: z.array(z.number()),
//   message_last_post: z.boolean(),
//   website_message_ids: z.array(z.any()),
//   create_uid: z.array(z.union([z.number(), z.string()])),
//   create_date: z.coerce.date(),
//   write_uid: z.array(z.union([z.number(), z.string()])),
//   write_date: z.coerce.date(),
//   is_direct_manager: z.boolean(),
//   message_is_follower: z.boolean(),
//   message_partner_ids: z.array(z.number()),
//   message_channel_ids: z.array(z.any()),
//   message_unread: z.boolean(),
//   message_unread_counter: z.number(),
//   message_needaction: z.boolean(),
//   message_needaction_counter: z.number(),
//   display_name: z.string(),
//   __last_update: z.coerce.date(),
// })
// export type Recommendation = z.infer<typeof RecommendationSchema>
