import {
  ApprovalsIcon,
  CalenderSpecialIcon,
  ClipboardIcon,
  DeliveryIcon,
  FileWithPenIcon,
  FileWithXIcon,
  ListAlternativeIcon,
  MailboxIcon,
  PaperIcon,
  PerformanceIcon,
  PersonWithLaptopIcon,
  PriceIcon,
  RemoteWorkIcon,
  RequestsIcon,
  SandClockIcon,
  SearchListIcon,
  StampIcon,
  TabletAltIcon,
  TabletIcon,
  TagWithXIcon,
  TimeIcon,
  TimeWithScreenIcon,
  TimerStartIcon,
  VacationIcon,
  WorkTimeIcon,
  WorkingHomeIcon,
  WritingNoteIcon,
  TimeBlueIcon,
} from "@icons"

export const infoIcons = {
  RequestsIcon,
  ApprovalsIcon,
  VacationIcon,
  PerformanceIcon,
  RemoteWorkIcon,
  TimeIcon,
  all_requests: ListAlternativeIcon,
  pending_requests: CalenderSpecialIcon,
  refused_requests: ClipboardIcon,
  PaperIcon,
  SandClockIcon,
  done_requests: StampIcon,
  TimeWithScreenIcon,
  WorkTimeIcon,
  PersonWithLaptopIcon,
  WorkingHomeIcon,
  TimerStartIcon,
  SearchListIcon,
  MailboxIcon,
  WritingNoteIcon,
  DeliveryIcon,
  TabletIcon,
  TabletAltIcon,
  FileWithXIcon,
  TagWithXIcon,
  PriceIcon,
  FileWithPenIcon,
  TimeBlueIcon,
} as const

export const arabicTitles = {
  pending_requests: "الطلبات تحت الاجراء",
  done_requests: "الطلبات المعتمدة",
  refused_requests: "الطلبات المرفوضة",
  all_requests: "كل الطلبات",
} as const
