import {
  ApprovalsIcon,
  CalenderSpecialIcon,
  ClipboardIcon,
  DeliveryIcon,
  FileWithPenIcon,
  FileWithXIcon,
  ListAlternativeIcon,
  MailboxIcon,
  PaperIcon,
  PerformanceIcon,
  PersonWithLaptopIcon,
  PriceIcon,
  RemoteWorkIcon,
  RequestsIcon,
  SandClockIcon,
  SearchListIcon,
  StampIcon,
  TabletAltIcon,
  TabletIcon,
  TagWithXIcon,
  TimeBlueIcon,
  TimeIcon,
  TimeWithScreenIcon,
  TimerStartIcon,
  VacationIcon,
  WorkTimeIcon,
  WorkingHomeIcon,
  WritingNoteIcon,
} from "@icons"

export const infoIcons = {
  RequestsIcon,
  ApprovalsIcon,
  VacationIcon,
  PerformanceIcon,
  RemoteWorkIcon,
  TimeIcon,
  all_holidays: ListAlternativeIcon,
  pending_holidays_requests: CalenderSpecialIcon,
  refused_cancelled_holidays_requests: ClipboardIcon,
  old_holidays_stock: PaperIcon,
  current_holidays_stock: SandClockIcon,
  done_holidays_requests: StampIcon,
  pending_authorisation_requests: SandClockIcon,
  done_authorisation_requests: StampIcon,
  refused_cancelled_authorisation_requests: ClipboardIcon,
  all_authorisation: ListAlternativeIcon,
  current_distance_work_stock: SandClockIcon,
  pending_distance_work_requests: CalenderSpecialIcon,
  done_distance_work_requests: StampIcon,
  refused_distance_work_requests: ClipboardIcon,
  all_distance_work_requests: ListAlternativeIcon,
  pending_change_bank_account_requests: SandClockIcon,
  refuse_change_bank_account_requests: ClipboardIcon,
  done_change_bank_account_requests: StampIcon,
  all_change_bank_account_requests: ListAlternativeIcon,
  pending_salary_request_requests: SandClockIcon,
  refuse_salary_request_requests: ClipboardIcon,
  done_salary_request_requests: StampIcon,
  all_salary_request_requests: ListAlternativeIcon,
  deputations_balance: SandClockIcon,
  pending_deputations_requests: CalenderSpecialIcon,
  done_deputations_requests: StampIcon,
  refused_cancelled_deputations_requests: ClipboardIcon,
  all_deputations_requests: ListAlternativeIcon,
  pending_overtime_assignment_requests: CalenderSpecialIcon,
  done_overtime_assignment_requests: StampIcon,
  refused_overtime_assignment_requests: ClipboardIcon,
  all_overtime_assignment_requests: ListAlternativeIcon,
  pending_overtime_request_requests: CalenderSpecialIcon,
  done_overtime_request_requests: StampIcon,
  refused_overtime_request_requests: ClipboardIcon,
  all_overtime_request_requests: ListAlternativeIcon,
  pending_passport_request_requests: CalenderSpecialIcon,
  done_passport_request_requests: StampIcon,
  refused_passport_request_requests: ClipboardIcon,
  all_passport_request_requests: ListAlternativeIcon,
  pending_employee_members_requests: CalenderSpecialIcon,
  done_employee_members_requests: StampIcon,
  refused_employee_members_requests: ClipboardIcon,
  all_employee_members_requests: ListAlternativeIcon,
  pending_medical_insurance_requests: CalenderSpecialIcon,
  done_medical_insurance_requests: StampIcon,
  refuse_cancel_medical_insurance_requests: ClipboardIcon,
  all_medical_insurance_requests: ListAlternativeIcon,
  pending_purchase_request_requests: CalenderSpecialIcon,
  done_purchase_request_requests: StampIcon,
  refuse_cancel_purchase_request_requests: ClipboardIcon,
  all_purchase_request_requests: ListAlternativeIcon,
  pending_custody_requests: SandClockIcon,
  done_custody_requests: StampIcon,
  refuse_cancel_custody_requests: ClipboardIcon,
  all_custody_requests: ListAlternativeIcon,
  pending_custody_close_requests: SandClockIcon,
  refuse_cancel_custody_close_requests: ClipboardIcon,
  done_custody_close_requests: StampIcon,
  all_custody_close_requests: ListAlternativeIcon,
  trainings_public: ListAlternativeIcon,
  pending_training_request_requests: CalenderSpecialIcon,
  done_training_request_requests: StampIcon,
  refused_cancelled_training_request_requests: ClipboardIcon,
  all_training_request_requests: ListAlternativeIcon,

  TimeWithScreenIcon,
  WorkTimeIcon,
  PersonWithLaptopIcon,
  WorkingHomeIcon,
  TimerStartIcon,
  SearchListIcon,
  MailboxIcon,
  WritingNoteIcon,
  DeliveryIcon,
  TabletIcon,
  TabletAltIcon,
  FileWithXIcon,
  TagWithXIcon,
  PriceIcon,
  FileWithPenIcon,
  TimeBlueIcon,
} as const

export const arabicTitles = {
  pending_requests: "الطلبات تحت الاجراء",
  done_requests: "الطلبات المعتمدة",
  refused_requests: "الطلبات المرفوضة",
  all_requests: "كل الطلبات",
  current_holidays_stock: "الرصيد الحالي",
  old_holidays_stock: "الرصيد ما قبل اللائحة",
  pending_holidays_requests: "الاجازات تحت الإجراء",
  done_holidays_requests: "الاجازات المعتمدة",
  refused_cancelled_holidays_requests: "المرفوضة /  والملغاة",
  all_holidays: "كل الاجازات",
  pending_authorisation_requests: "الاستئذانات تحت الإجراء",
  done_authorisation_requests: "الاستئذانات المعتمدة",
  refused_cancelled_authorisation_requests: "المرفوضة /  والملغاة",
  all_authorisation: "كل الاستئذانات",
  current_distance_work_stock: "الرصيد الحالي",
  pending_distance_work_requests: "الطلبات تحت الإجراء",
  done_distance_work_requests: "الطلبات المعتمدة",
  refused_distance_work_requests: "الطلبات المرفوضة",
  all_distance_work_requests: "كل الطلبات",
  pending_change_bank_account_requests: "التعريفات تحت الإجراء",
  refuse_change_bank_account_requests: "التعريفات المرفوضة",
  done_change_bank_account_requests: "التعريفات المعتمدة",
  all_change_bank_account_requests: "كل التعريفات",
  pending_salary_request_requests: "الخطابات تحت الإجراء",
  refuse_salary_request_requests: "الخطابات المرفوضة",
  done_salary_request_requests: "الخطابات المعتمدة",
  all_salary_request_requests: "كل الخطابات",
  deputations_balance: "الرصيد الحالي",
  pending_deputations_requests: "الانتدابات تحت الإجراء",
  done_deputations_requests: "الانتدابات المعتمدة",
  refused_cancelled_deputations_requests: "المرفوضة /  والملغاة",
  all_deputations_requests: "كل الانتدابات",
  pending_overtime_assignment_requests: "الطلبات تحت الإجراء",
  done_overtime_assignment_requests: "الطلبات المعتمدة",
  refused_overtime_assignment_requests: "الطلبات المرفوضة",
  all_overtime_assignment_requests: "كل الطلبات",
  pending_overtime_request_requests: "الطلبات تحت الإجراء",
  done_overtime_request_requests: "الطلبات المعتمدة",
  refused_overtime_request_requests: "الطلبات المرفوضة",
  all_overtime_request_requests: "كل الطلبات",
  pending_passport_request_requests: "الطلبات تحت الإجراء",
  done_passport_request_requests: "الطلبات المعتمدة",
  refused_passport_request_requests: "الطلبات المرفوضة",
  all_passport_request_requests: "كل الطلبات",
  pending_employee_members_requests: "الطلبات تحت الإجراء",
  done_employee_members_requests: "الطلبات المعتمدة",
  refused_employee_members_requests: "الطلبات المرفوضة",
  all_employee_members_requests: "كل الطلبات",
  pending_medical_insurance_requests: "التأمينات تحت الإجراء",
  done_medical_insurance_requests: "التأمينات المعتمدة",
  refuse_cancel_medical_insurance_requests: "المرفوضة / الملغاة",
  all_medical_insurance_requests: "كل التأمينات",
  pending_purchase_request_requests: "الطلبات تحت الإجراء",
  done_purchase_request_requests: "الطلبات المعتمدة",
  refuse_cancel_purchase_request_requests: "الطلبات المرفوضة",
  all_purchase_request_requests: "كل الطلبات",
  pending_custody_requests: "الطلبات تحت الإجراء",
  done_custody_requests: "الطلبات المعتمدة",
  refuse_cancel_custody_requests: "المرفوضة / الملغاة",
  all_custody_requests: "كل الطلبات",
  pending_custody_close_requests: "الطلبات تحت الإجراء",
  refuse_cancel_custody_close_requests: "المرفوضة / الملغاة",
  done_custody_close_requests: "الطلبات المعتمدة",
  all_custody_close_requests: "كل الطلبات",
  trainings_public: "الدورات الداخلية",
  pending_training_request_requests: "الدورات تحت الإجراء",
  done_training_request_requests: "الدورات المعتمدة",
  refused_cancelled_training_request_requests: "الدورات المرفوضة",
  all_training_request_requests: "كل الدورات",
} as const
