import * as z from "zod"

export const MedicalInsuranceElementSchema = z.object({
  id: z.any(),
  name: z.any(),
  date: z.any(),
  employee_id: z.any(),
  request_type: z.any(),
  attachment_ids: z.any(),
  relative_relation: z.any(),
  individual_complete_name: z.any(),
  state: z.any(),
  reason: z.any(),
  active: z.any(),
  individual_english_name: z.any(),
  medical_insurance_type_id: z.any(),
  medical_insurance_category_id: z.any(),
  insurance_amount: z.any(),
  coverage: z.any(),
  date_from: z.any(),
  date_to: z.any(),
  website_message_ids: z.any(),
  message_follower_ids: z.any(),
  message_ids: z.any(),
  message_last_post: z.any(),
  create_uid: z.any(),
  create_date: z.any(),
  write_uid: z.any(),
  write_date: z.any(),
  message_is_follower: z.any(),
  message_partner_ids: z.any(),
  message_channel_ids: z.any(),
  message_unread: z.any(),
  message_unread_counter: z.any(),
  message_needaction: z.any(),
  message_needaction_counter: z.any(),
  display_name: z.any(),
  __last_update: z.any(),
})
export type MedicalInsuranceElement = z.infer<
  typeof MedicalInsuranceElementSchema
>

// export const MedicalInsuranceElementSchema = z.object({
//   id: z.number(),
//   name: z.string(),
//   date: z.string(),
//   employee_id: z.array(z.union([z.string(), z.number()])),
//   request_type: z.string(),
//   attachment_ids: z.array(z.number()),
//   relative_relation: z.string(),
//   individual_complete_name: z.string(),
//   state: z.string(),
//   reason: z.union([z.boolean(), z.string()]),
//   active: z.boolean(),
//   individual_english_name: z.string(),
//   medical_insurance_type_id: z.array(z.union([z.string(), z.number()])),
//   medical_insurance_category_id: z.array(z.union([z.string(), z.number()])),
//   insurance_amount: z.number(),
//   coverage: z.union([z.boolean(), z.string()]),
//   date_from: z.union([z.boolean(), z.string()]),
//   date_to: z.union([z.boolean(), z.string()]),
//   website_message_ids: z.array(z.any()),
//   message_follower_ids: z.array(z.number()),
//   message_ids: z.array(z.number()),
//   message_last_post: z.boolean(),
//   create_uid: z.array(z.union([z.string(), z.number()])),
//   create_date: z.coerce.date(),
//   write_uid: z.array(z.union([z.string(), z.number()])),
//   write_date: z.coerce.date(),
//   message_is_follower: z.boolean(),
//   message_partner_ids: z.array(z.number()),
//   message_channel_ids: z.array(z.any()),
//   message_unread: z.boolean(),
//   message_unread_counter: z.number(),
//   message_needaction: z.boolean(),
//   message_needaction_counter: z.number(),
//   display_name: z.string(),
//   __last_update: z.coerce.date(),
// })
// export type MedicalInsuranceElement = z.infer<
//   typeof MedicalInsuranceElementSchema
// >
