import * as z from "zod"

export const CustodyElementSchema = z.object({
  id: z.any(),
  name: z.any(),
  custody_amount: z.any(),
  custody_type: z.any(),
  refuse_reason: z.any(),
  cancel_reason: z.any(),
  custody_reason_id: z.any(),
  custody_reason: z.any(),
  employee_id: z.any(),
  is_have_close_custody: z.any(),
  is_have_replace_custody: z.any(),
  state: z.any(),
  hide_payment_order: z.any(),
  payment_order_id: z.any(),
  order_date: z.any(),
  company_id: z.any(),
  account_id: z.any(),
  journal_id: z.any(),
  payment_state: z.any(),
  readonly_by_pass: z.any(),
  payment_move_line_ids: z.any(),
  check_custody_remain_amount: z.any(),
  active: z.any(),
  res_model: z.any(),
  is_from_mobile: z.any(),
  mobile_approvals_ids: z.any(),
  website_message_ids: z.any(),
  message_follower_ids: z.any(),
  message_ids: z.any(),
  message_last_post: z.any(),
  create_uid: z.any(),
  create_date: z.any(),
  write_uid: z.any(),
  write_date: z.any(),
  number: z.any(),
  sector_id: z.any(),
  administration_id: z.any(),
  job_id: z.any(),
  degree_id: z.any(),
  check_authority_owner: z.any(),
  custody_paid_amount: z.any(),
  custody_remain_amount: z.any(),
  bank_id: z.any(),
  acc_number: z.any(),
  is_dm: z.any(),
  payments_widget: z.any(),
  is_action_send: z.any(),
  account_move_number: z.any(),
  account_move_id: z.any(),
  department_global_id: z.any(),
  message_is_follower: z.any(),
  message_partner_ids: z.any(),
  message_channel_ids: z.any(),
  message_unread: z.any(),
  message_unread_counter: z.any(),
  message_needaction: z.any(),
  message_needaction_counter: z.any(),
  display_name: z.any(),
  __last_update: z.any(),
})
export type CustodyElement = z.infer<typeof CustodyElementSchema>

// export const CustodyElementSchema = z.object({
//   id: z.number(),
//   name: z.string(),
//   custody_amount: z.number(),
//   custody_type: z.string(),
//   refuse_reason: z.union([z.boolean(), z.string()]),
//   cancel_reason: z.boolean(),
//   custody_reason_id: z.array(z.union([z.number(), z.string()])),
//   custody_reason: z.string(),
//   employee_id: z.array(z.union([z.number(), z.string()])),
//   is_have_close_custody: z.boolean(),
//   is_have_replace_custody: z.boolean(),
//   state: z.string(),
//   hide_payment_order: z.boolean(),
//   payment_order_id: z.boolean(),
//   order_date: z.string(),
//   company_id: z.array(z.union([z.number(), z.string()])),
//   account_id: z.array(z.union([z.number(), z.string()])),
//   journal_id: z.boolean(),
//   payment_state: z.boolean(),
//   readonly_by_pass: z.boolean(),
//   payment_move_line_ids: z.array(z.any()),
//   check_custody_remain_amount: z.boolean(),
//   active: z.boolean(),
//   res_model: z.string(),
//   is_from_mobile: z.boolean(),
//   mobile_approvals_ids: z.array(z.any()),
//   website_message_ids: z.array(z.any()),
//   message_follower_ids: z.array(z.number()),
//   message_ids: z.array(z.number()),
//   message_last_post: z.boolean(),
//   create_uid: z.array(z.union([z.number(), z.string()])),
//   create_date: z.coerce.date(),
//   write_uid: z.array(z.union([z.number(), z.string()])),
//   write_date: z.coerce.date(),
//   number: z.string(),
//   sector_id: z.array(z.union([z.number(), z.string()])),
//   administration_id: z.array(z.union([z.number(), z.string()])),
//   job_id: z.array(z.union([z.number(), z.string()])),
//   degree_id: z.array(z.union([z.number(), z.string()])),
//   check_authority_owner: z.boolean(),
//   custody_paid_amount: z.number(),
//   custody_remain_amount: z.number(),
//   bank_id: z.array(z.union([z.number(), z.string()])),
//   acc_number: z.string(),
//   is_dm: z.boolean(),
//   payments_widget: z.string(),
//   is_action_send: z.boolean(),
//   account_move_number: z.string(),
//   account_move_id: z.boolean(),
//   department_global_id: z.array(z.union([z.number(), z.string()])),
//   message_is_follower: z.boolean(),
//   message_partner_ids: z.array(z.number()),
//   message_channel_ids: z.array(z.any()),
//   message_unread: z.boolean(),
//   message_unread_counter: z.number(),
//   message_needaction: z.boolean(),
//   message_needaction_counter: z.number(),
//   display_name: z.string(),
//   __last_update: z.coerce.date(),
// })
// export type CustodyElement = z.infer<typeof CustodyElementSchema>
